<START_def> ::= <DEFINE-THRESHOLD-LEVEL_def> <MLC-ALGORITHMS_def>
<MLC-ALGORITHMS_def> ::= BR <ALGS-SLC_def> | CC <ALGS-SLC_def> | LP <ALGS-SLC_def> | <BRq_def> <ALGS-SLC_def> | <CCq_def> <ALGS-SLC_def> | FW <ALGS-SLC_def> | RT <ALGS-SLC_def> | PCC <ALGS-SLC_def> | <CT_def> <ALGS-SLC_def>| <MCC_def> <ALGS-SLC_def>| <CDT_def> <ALGS-SLC_def> | <CDN_def> <ALGS-SLC_def> | <PS_def> <ALGS-SLC_def> | <PSt_def> <ALGS-SLC_def> | <RAkEL_def> <ALGS-SLC_def> | <RAkELd_def> <ALGS-SLC_def> | <BCC_def> <ALGS-SLC_def> | <PMCC_def> <ALGS-SLC_def> | <ML-BPNN_def> | <ML-DBPNN_def> <ML-BPNN_def> | <HOMER_def> <META-MLC_def> | <MBR_def>
<ALGS-SLC_def> ::= <ALGS-SLC-WITH-FS_def> | <ALG-TYPE-WITHOUT-FS_def> | <META-SLC_def>
<ALGS-SLC-WITH-FS_def> ::= <ASC_def> <ALG-TYPE-WITHOUT-FS_def>
<ASC_def> ::= ASC <sm_def>
<ALG-TYPE-WITHOUT-FS_def> ::= <J48_def> | DecisionStump |  <RandomForest_def> | <RandomTree_def> | <REPTree_def> | <DT_def> | <JRip_def> | <OneR_def> | <PART_def> | ZeroR | <KNN_def> | <KStar_def> | <VotedPerceptron_def> | <MultiLayerPerc_def> | <SeqMinOptimization_def> | <StocGradDescent_def> | <LR_def> | <NB_def> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_def> | <SimpleLogistic_def>
<J48_def> ::= J48 <J48-Complement_def> <J48-Basics_def>
<J48-Complement_def> ::= <cf_def> <sr_def>
<cf_def> ::= 0.25
<sr_def> ::= True
<J48-Basics_def> ::= <mno_def> <ct_def> <bs_def> <umc_def> <ul_def>
<mno_def> ::= 2
<ct_def> ::= True
<bs_def> ::= False
<umc_def> ::= True
<ul_def> ::= False
<LogisticModelTrees_def> ::= LogisticModelTrees <mno-lmt_def> <cn_def> <sor_def> <fr_def> <eop_def> <uaic_def> <wtb_activate_def>
<mno-lmt_def> ::= 15
<cn_def> ::= False
<sor_def> ::= False
<fr_def> ::= True
<eop_def> ::= False
<wtb_activate_def> ::= False
<uaic_def> ::= False
<wtb_def> ::= 0.0
<RandomForest_def> ::= RandomForest <nt_def> <nf_def>  <md_def>
<nt_def> ::= 100
<nf_def> ::= 0
<md_def> ::= 0
<RandomTree_def> ::= RandomTree <mw_def> <nfbgt_def> <nf_def>  <md_def>
<mw_def> ::= 1
<nfbgt_def> ::= 0
<REPTree_def> ::= REPTree <var_def> <mw-rep_def> <up_def>  <md-rep_def>
<mw-rep_def> ::= 2
<var_def> ::= 0.001
<up_def> ::= False
<md-rep_def> ::= -1
<DT_def> ::= DT <em_def> <uibk_def> <sm_def> <crv_def>
<em_def> ::= acc
<uibk_def> ::= False
<sm_def> ::= BestFirst
<crv_def> ::= 1
<JRip_def> ::= JRip <mtw_def> <cer_def> <up_def> <o_def>
<mtw_def> ::= 2.0
<cer_def> ::= True
<o_def> ::= 2
<OneR_def> ::= OneR <mbs_def>
<mbs_def> ::= 6
<PART_def> ::= PART <PART-BASICS_def> <PART-CONSTRAINTS_def>
<PART-BASICS_def> ::= <mno_def> <bs_def>
<PART-CONSTRAINTS_def> ::= False
<KNN_def> ::= KNN <k_nn_def> <loo_def> <dw_def>
<k_nn_def> ::= 1
<loo_def> ::= False
<dw_def> ::= None
<KStar_def> ::= KStar <gb_def> <eab_def> <mm_def>
<gb_def> ::= 20
<eab_def> ::= False
<mm_def> ::= a
<VotedPerceptron_def> ::= VotedPerceptron <i_def> <mk_def> <e_def>
<i_def> ::= 1
<mk_def> ::= 10000
<e_def> ::= 1.0
<MultiLayerPerc_def> ::= MultiLayerPerc <lr_def> <m_def> <nhn_def> <n2b_def> <reset_def> <decay_def>
<lr_def> ::= 0.3
<m_def> ::= 0.2
<nhn_def> ::= a
<n2b_def> ::= True
<reset_def> ::= True
<decay_def> ::= False
<StocGradDescent_def> ::= StocGradDescent <lf_def> <lr_sgd_def> <nn_def> <nrmv_def> <r_def>
<lf_def> ::= 0
<lr_sgd_def> ::= 0.01
<nn_def> ::= False
<nrmv_def> ::= False
<r_def> ::= 0.0001
<LR_def> ::= LogisticRegression <r-lr_def>
<r-lr_def> ::= 0.00000001
<SimpleLogistic_def> ::= SimpleLogistic <ucv_def> <uaic_def> <wtb_activate_def>
<ucv_def> ::= True
<SeqMinOptimization_def> ::= SeqMinOptimization <c_def> <ft_def> <bcm_def> <kernel_def>
<c_def> ::= 1.0
<ft_def> ::= 0
<bcm_def> ::= False
<kernel_def> ::= <poly_kern_def> <exp_def> <ulo_def>
<poly_kern_def> ::= PolyKernel
<exp_def> ::= 1.0
<ulo_def> ::= True
<NB_def> ::= NaiveBayes <NB-Parameters_def>
<NB-Parameters_def> ::= None
<META-SLC_def> ::= <LWL_def> <ALG-WEIGHTED-TYPE_def> | RandomSubspace <sss_def> <ni_random_methods_def> <ALG-TYPE-WITHOUT-FS_def> | RandomCommittee <ni_random_methods_def> <ALG-TYPE_RC_def> | <Bagging_def> <ni_ada_and_bagging_def> <ALG-TYPE-WITHOUT-FS_def> | <AdaM1_def> <ni_ada_and_bagging_def> <ALG-WEIGHTED-TYPE_def> | <STACKING_def> | <VOTING_def>
<ALG-WEIGHTED-TYPE_def> ::= <J48_def> | DecisionStump | <RandomForest_def> | <RandomTree_def> | <REPTree_def> | <DT_def> | <JRip_def> | <PART_def> | ZeroR | <KNN_def> | <NB_def> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_def> |  <SeqMinOptimization_def> | <SimpleLogistic_def>
<LWL_def> ::= LWL <k_lwl_activate_def> <wk_activate_def>
<k_lwl_activate_def> ::= False
<k_lwl_def> ::= -1
<wk_activate_def> ::= False
<sss_def> ::= 0.5
<ni_random_methods_def> ::= 10
<ALG-TYPE_RC_def> ::= <RandomForest_def> | <RandomTree_def> | <REPTree_def> | <StocGradDescent_def> | <MultiLayerPerc_def>
<Bagging_def> ::= BaggingSLC <BaggingSLC_BASICS_def>
<BaggingSLC_BASICS_def> ::= False <bsp-bagg_def>
<bsp-bagg_def> ::= 100
<AdaM1_def> ::= AdaM1 <wt_def> <ur_def>
<wt_def> ::= 100
<ni_ada_and_bagging_def> ::= 10
<ur_def> ::= False
<STACKING_def> ::= Stacking <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | Stacking <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | Stacking <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | Stacking <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def>
<VOTING_def> ::= <Vote_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | <Vote_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | <Vote_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> | <Vote_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def> <ALG-TYPE-WITHOUT-FS_def>
<Vote_def> ::= Vote <cr_def>
<cr_def> ::= AVG
<BRq_def> ::= BRq <dsr_def>
<CCq_def> ::= CCq <dsr_def>
<dsr_def> ::= 0.75
<MCC_def> ::= MCC <chi_MCC_def> <ii_def> <eval_metrics_def>
<chi_MCC_def>::= 0
<ii_def> ::= 10
<eval_metrics_def> ::= Exact-match
<BCC_def> ::= BCC <dp_complete_def>
<dp_complete_def> ::= Ibf
<PMCC_def> ::= PMCC <B_def> <ts_def> <ii_def> <chi_PMCC_def> <ps_def> <eval_metrics_def>
<B_def> ::= 0.03
<ts_def> ::= 0
<chi_PMCC_def> ::= 50
<ps_def> ::= 10
<CT_def> ::= CT <chi_CT_def> <w_def> <dp_def> <ii_def> <eval_metrics_def>
<chi_CT_def> ::= 0
<dp_def> ::= Ibf
<w_def> ::= -1 <d_def>
<d_def> ::= 1
<CDN_def> ::= CDN <i_cdn_cdt_def> <ci_def>
<i_cdn_cdt_def> ::= 1000
<ci_def> ::= 100
<CDT_def> ::= CDT <w_def> <dp-cdt_def> <i_cdn_cdt_def> <ci_def>
<dp-cdt_def> ::= None
<PS_def> ::= PS <sv_def> <pv_def>
<PSt_def> ::= PSt <sv_def> <pv_def>
<sv_def> ::= 0
<pv_def> ::= 0
<RAkELd_def> ::= RAkELd <les_def> <sv_def> <pv_def>
<RAkEL_def> ::= RAkEL <sre_def> <les_def> <sv_def> <pv_def>
<les_def> ::= 3
<sre_def> ::= 10
<ML-BPNN_def> ::= ML-BPNN <ne_def> <nhu_bpnn_def> <lr_bpnn_def> <m_bpnn_def>
<ne_def> ::= 100
<nhu_bpnn_def> ::= 10
<lr_bpnn_def> ::= 0.1
<m_bpnn_def> ::=  0.1
<ML-DBPNN_def> ::= ML-DBPNN <ne_def> <nhu_bpnn_def> <lr_bpnn_def> <m_bpnn_def> <rbm_def>		
<rbm_def> ::= 2
<HOMER_def> ::= HOMER <t_def> <k_homer_def>
<t_def> ::= BalancedClustering
<k_homer_def> ::= 3
<META-MLC_def> ::= BR <ALGS-SLC_def> | CC <ALGS-SLC_def> | LP <ALGS-SLC_def>
<MBR_def> ::= MBR BR <ALGS-SLC_def>
<DEFINE-THRESHOLD-LEVEL_def> ::= threshold <predtshd_def>
<predtshd_def> ::= PCut1
