<START_i> ::= <DEFINE-THRESHOLD-LEVEL_i> <MLC-ALGORITHMS_i>
<MLC-ALGORITHMS_i> ::= BR <ALGS-SLC_i> | CC <ALGS-SLC_i> | LP <ALGS-SLC_i> | <BRq_i> <ALGS-SLC_i> | <CCq_i> <ALGS-SLC_i> | FW <ALGS-SLC_i> | RT <ALGS-SLC_i> | PCC <ALGS-SLC_i> | <CT_i> <ALGS-SLC_i>| <MCC_i> <ALGS-SLC_i>| <CDT_i> <ALGS-SLC_i> | <CDN_i> <ALGS-SLC_i> | <PS_i> <ALGS-SLC_i> | <PSt_i> <ALGS-SLC_i> | <RAkEL_i> <ALGS-SLC_i> | <RAkELd_i> <ALGS-SLC_i> | <BCC_i> <ALGS-SLC_i> | <PMCC_i> <ALGS-SLC_i> | <ML-BPNN_i> | <ML-DBPNN_i> <ML-BPNN_i> | <HOMER_i> <META-MLC_i> | <MBR_i>
<ALGS-SLC_i> ::= <ALGS-SLC-WITH-FS_i> | <ALG-TYPE-WITHOUT-FS_i> | <META-SLC_i>
<ALGS-SLC-WITH-FS_i> ::= <ASC_i> <ALG-TYPE-WITHOUT-FS_i>
<ASC_i> ::= ASC <sm_i>
<ALG-TYPE-WITHOUT-FS_i> ::= <J48_i> | DecisionStump |  <RandomForest_i> | <RandomTree_i> | <REPTree_i> | <DT_i> | <JRip_i> | <OneR_i> | <PART_i> | ZeroR | <KNN_i> | <KStar_i> | <VotedPerceptron_i> | <MultiLayerPerc_i> | <SeqMinOptimization_i> | <StocGradDescent_i> | <LR_i> | <NB_i> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_i> | <SimpleLogistic_i>
<J48_i> ::= J48 <J48-Complement_i> <J48-Basics_i>
<J48-Complement_i> ::= <cf_i> <sr_i>
<cf_i> ::= 0.25
<sr_i> ::= True
<J48-Basics_i> ::= <mno_i> <ct_i> <bs_i> <umc_i> <ul_i>
<mno_i> ::= RANDINT_TYPE0(1,64)
<ct_i> ::= True
<bs_i> ::= False
<umc_i> ::= True
<ul_i> ::= False
<LogisticModelTrees_i> ::= LogisticModelTrees <mno-lmt_i> <cn_i> <sor_i> <fr_i> <eop_i> <uaic_i> <wtb_activate_i>
<mno-lmt_i> ::= RANDINT_TYPE0(1,64)
<cn_i> ::= False
<sor_i> ::= False
<fr_i> ::= True
<eop_i> ::= False
<wtb_activate_i> ::= False
<uaic_i> ::= False
<wtb_i> ::= 0.0
<RandomForest_i> ::= RandomForest <nt_i> <nf_i>  <md_i>
<nt_i> ::= RANDINT_TYPE0(2,256)
<nf_i> ::= RANDINT_TYPE0(2,32)
<md_i> ::= RANDINT_TYPE0(2,20)
<RandomTree_i> ::= RandomTree <mw_i> <nfbgt_i> <nf_i>  <md_i>
<mw_i> ::= RANDINT_TYPE0(1,64)
<nfbgt_i> ::= <growing_the_tree_and_backfitting>
<growing_the_tree_and_backfitting> ::= RANDINT_TYPE0(0,5)
<REPTree_i> ::= REPTree <var_i> <mw-rep_i> <up_i>  <md-rep_i>
<mw-rep_i> ::= RANDINT_TYPE0(1,64)
<var_i> ::= 0.001
<up_i> ::= False
<md-rep_i> ::= RANDINT_TYPE0(0,20) 
<DT_i> ::= DT <em_i> <uibk_i> <sm_i> <crv_i>
<em_i> ::= acc
<uibk_i> ::= False
<sm_i> ::= BestFirst
<crv_i> ::= 1 | 2 | 3 | 4 
<JRip_i> ::= JRip <mtw_i> <cer_i> <up_i> <o_i>
<mtw_i> ::= 2.0
<cer_i> ::= True
<o_i> ::= RANDINT_TYPE0(1,5) 
<OneR_i> ::= OneR <mbs_i>
<mbs_i> ::= RANDINT_TYPE0(1,32)
<PART_i> ::= PART <PART-BASICS_i> <PART-CONSTRAINTS_i>
<PART-BASICS_i> ::= <mno_i> <bs_i>
<PART-CONSTRAINTS_i> ::= False
<KNN_i> ::= KNN <k_nn_i> <loo_i> <dw_i>
<k_nn_i> ::= RANDINT_TYPE0(1,64)
<loo_i> ::= False
<dw_i> ::= None
<KStar_i> ::= KStar <gb_i> <eab_i> <mm_i>
<gb_i> ::= RANDINT_TYPE0(1,100)
<eab_i> ::= False
<mm_i> ::= a
<VotedPerceptron_i> ::= VotedPerceptron <i_i> <mk_i> <e_i>
<i_i> ::= RANDINT_TYPE0(1,10)
<mk_i> ::= RANDINT_TYPE0(5000,50000)
<e_i> ::= 1.0
<MultiLayerPerc_i> ::= MultiLayerPerc <lr_i> <m_i> <nhn_i> <n2b_i> <reset_i> <decay_i>
<lr_i> ::= 0.3
<m_i> ::= 0.2
<nhn_i> ::= a
<n2b_i> ::= True
<reset_i> ::= True
<decay_i> ::= False
<StocGradDescent_i> ::= StocGradDescent <lf_i> <lr_sgd_i> <nn_i> <nrmv_i> <r_i>
<lf_i> ::= 0
<lr_sgd_i> ::= 0.01
<nn_i> ::= False
<nrmv_i> ::= False
<r_i> ::= 0.0001
<LR_i> ::= LogisticRegression <r-lr_i>
<r-lr_i> ::= 0.00000001
<SimpleLogistic_i> ::= SimpleLogistic <ucv_i> <uaic_i> <wtb_activate_i>
<ucv_i> ::= True
<SeqMinOptimization_i> ::= SeqMinOptimization <c_i> <ft_i> <bcm_i> <kernel_i>
<c_i> ::= 1.0
<ft_i> ::= 0
<bcm_i> ::= False
<kernel_i> ::= <poly_kern_i> <exp_i> <ulo_i>
<poly_kern_i> ::= PolyKernel
<exp_i> ::= 1.0
<ulo_i> ::= True
<NB_i> ::= NaiveBayes <NB-Parameters_i>
<NB-Parameters_i> ::= None
<META-SLC_i> ::= <LWL_i> <ALG-WEIGHTED-TYPE_i> | RandomSubspace <sss_i> <ni_random_methods_i> <ALG-TYPE-WITHOUT-FS_i> | RandomCommittee <ni_random_methods_i> <ALG-TYPE_RC_i> | <Bagging_i> <ni_ada_and_bagging_i> <ALG-TYPE-WITHOUT-FS_i> | <AdaM1_i> <ni_ada_and_bagging_i> <ALG-WEIGHTED-TYPE_i> | <STACKING_i> | <VOTING_i>
<ALG-WEIGHTED-TYPE_i> ::= <J48_i> | DecisionStump | <RandomForest_i> | <RandomTree_i> | <REPTree_i> | <DT_i> | <JRip_i> | <PART_i> | ZeroR | <KNN_i> | <NB_i> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_i> |  <SeqMinOptimization_i> | <SimpleLogistic_i>
<LWL_i> ::= LWL <k_lwl_activate_i> <wk_activate_i>
<k_lwl_activate_i> ::= False
<k_lwl_i> ::= -1 | 10| 30 | 60 | 90 | 120
<wk_activate_i> ::= False
<sss_i> ::= 0.5
<ni_random_methods_i> ::= RANDINT_TYPE0(2,64)
<ALG-TYPE_RC_i> ::= <RandomForest_i> | <RandomTree_i> | <REPTree_i> | <StocGradDescent_i> | <MultiLayerPerc_i>
<Bagging_i> ::= BaggingSLC <BaggingSLC_BASICS_i>
<BaggingSLC_BASICS_i> ::= False <bsp-bagg_i>
<bsp-bagg_i> ::= RANDINT_TYPE0(10,100)
<AdaM1_i> ::= AdaM1 <wt_i> <ur_i>
<wt_i> ::= RANDINT_TYPE0(50,100) 
<ni_ada_and_bagging_i> ::= RANDINT_TYPE0(2,128)
<ur_i> ::= False
<STACKING_i> ::= Stacking <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | Stacking <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | Stacking <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | Stacking <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i>
<VOTING_i> ::= <Vote_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | <Vote_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | <Vote_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> | <Vote_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i> <ALG-TYPE-WITHOUT-FS_i>
<Vote_i> ::= Vote <cr_i>
<cr_i> ::= AVG
<BRq_i> ::= BRq <dsr_i>
<CCq_i> ::= CCq <dsr_i>
<dsr_i> ::= 0.75
<MCC_i> ::= MCC <chi_MCC_i> <ii_i> <eval_metrics_i>
<chi_MCC_i>::=  RANDINT_TYPE0(2,1500)
<ii_i> ::= RANDINT_TYPE0(2,100)
<eval_metrics_i> ::= Exact-match
<BCC_i> ::= BCC <dp_complete_i>
<dp_complete_i> ::= Ibf
<PMCC_i> ::= PMCC <B_i> <ts_i> <ii_i> <chi_PMCC_i> <ps_i> <eval_metrics_i>
<B_i> ::= 0.03
<ts_i> ::= 0
<chi_PMCC_i> ::= RANDINT_TYPE0(51,1500)
<ps_i> ::= RANDINT_TYPE0(1,50)
<CT_i> ::= CT <chi_CT_i> <w_i> <dp_i> <ii_i> <eval_metrics_i>
<chi_CT_i> ::= RANDINT_TYPE0(2,1500)
<dp_i> ::= Ibf
<w_i> ::= 0 1 | -1 <d_i>
<d_i> ::= RANDINT_TYPE1(1,SQRT(L)+1)
<CDN_i> ::= CDN <i_cdn_cdt_i> <ci_i>
<i_cdn_cdt_i> ::= RANDINT_TYPE0(101,1000)
<ci_i> ::= RANDINT_TYPE0(1,100)
<CDT_i> ::= CDT <w_i> <dp-cdt_i> <i_cdn_cdt_i> <ci_i>
<dp-cdt_i> ::= None
<PS_i> ::= PS <sv_i> <pv_i>
<PSt_i> ::= PSt <sv_i> <pv_i>
<sv_i> ::= RANDINT_TYPE0(0,5)
<pv_i> ::= RANDINT_TYPE0(1,5) 
<RAkELd_i> ::= RAkELd <les_i> <sv_i> <pv_i>
<RAkEL_i> ::= RAkEL <sre_i> <les_i> <sv_i> <pv_i>
<les_i> ::= RANDINT_TYPE2(1,L/2)
<sre_i> ::= RANDINT_TYPE3(2,min(2L;100))
<ML-BPNN_i> ::= ML-BPNN <ne_i> <nhu_bpnn_i> <lr_bpnn_i> <m_bpnn_i>
<ne_i> ::= RANDINT_TYPE0(10,1000)
<nhu_bpnn_i> ::=  RANDINT_TYPE4((0.2,1.0)*n_attributes)
<lr_bpnn_i> ::= 0.1
<m_bpnn_i> ::=  0.1
<ML-DBPNN_i> ::= ML-DBPNN <ne_i> <nhu_bpnn_i> <lr_bpnn_i> <m_bpnn_i> <rbm_i>		
<rbm_i> ::= RANDINT_TYPE0(2,5)
<HOMER_i> ::= HOMER <t_i> <k_homer_i>
<t_i> ::= BalancedClustering
<k_homer_i> ::= RANDINT_TYPE6(2,L-1)
<META-MLC_i> ::= BR <ALGS-SLC_i> | CC <ALGS-SLC_i> | LP <ALGS-SLC_i>
<MBR_i> ::= MBR BR <ALGS-SLC_i>
<DEFINE-THRESHOLD-LEVEL_i> ::= threshold <predtshd_i>
<predtshd_i> ::= PCut1
