<START_r> ::= <DEFINE-THRESHOLD-LEVEL_r> <MLC-ALGORITHMS_r>
<MLC-ALGORITHMS_r> ::= BR <ALGS-SLC_r> | CC <ALGS-SLC_r> | LP <ALGS-SLC_r> | <BRq_r> <ALGS-SLC_r> | <CCq_r> <ALGS-SLC_r> | FW <ALGS-SLC_r> | RT <ALGS-SLC_r> | PCC <ALGS-SLC_r> | <CT_r> <ALGS-SLC_r>| <MCC_r> <ALGS-SLC_r>| <CDT_r> <ALGS-SLC_r> | <CDN_r> <ALGS-SLC_r> | <PS_r> <ALGS-SLC_r> | <PSt_r> <ALGS-SLC_r> | <RAkEL_r> <ALGS-SLC_r> | <RAkELd_r> <ALGS-SLC_r> | <BCC_r> <ALGS-SLC_r> | <PMCC_r> <ALGS-SLC_r> | <ML-BPNN_r> | <ML-DBPNN_r> <ML-BPNN_r> | <HOMER_r> <META-MLC_r> | <MBR_r>
<ALGS-SLC_r> ::= <ALGS-SLC-WITH-FS_r> | <ALG-TYPE-WITHOUT-FS_r> | <META-SLC_r>
<ALGS-SLC-WITH-FS_r> ::= <ASC_r> <ALG-TYPE-WITHOUT-FS_r>
<ASC_r> ::= ASC <sm_r>
<ALG-TYPE-WITHOUT-FS_r> ::= <J48_r> | DecisionStump |  <RandomForest_r> | <RandomTree_r> | <REPTree_r> | <DT_r> | <JRip_r> | <OneR_r> | <PART_r> | ZeroR | <KNN_r> | <KStar_r> | <VotedPerceptron_r> | <MultiLayerPerc_r> | <SeqMinOptimization_r> | <StocGradDescent_r> | <LR_r> | <NB_r> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_r> | <SimpleLogistic_r>
<J48_r> ::= J48 <J48-Complement_r> <J48-Basics_r>
<J48-Complement_r> ::= <cf_r> <sr_r>
<cf_r> ::= RANDFLOAT(0.0,1.0)
<sr_r> ::= True
<J48-Basics_r> ::= <mno_r> <ct_r> <bs_r> <umc_r> <ul_r>
<mno_r> ::= 2
<ct_r> ::= True
<bs_r> ::= False
<umc_r> ::= True
<ul_r> ::= False
<LogisticModelTrees_r> ::= LogisticModelTrees <mno-lmt_r> <cn_r> <sor_r> <fr_r> <eop_r> <uaic_r> <wtb_activate_r>
<mno-lmt_r> ::= 15
<cn_r> ::= False
<sor_r> ::= False
<fr_r> ::= True
<eop_r> ::= False
<wtb_activate_r> ::= False
<uaic_r> ::= False
<wtb_r> ::= RANDFLOAT(0.0,1.0)
<RandomForest_r> ::= RandomForest <nt_r> <nf_r>  <md_r>
<nt_r> ::= 100
<nf_r> ::= 0
<md_r> ::= 0
<RandomTree_r> ::= RandomTree <mw_r> <nfbgt_r> <nf_r>  <md_r>
<mw_r> ::= 1
<nfbgt_r> ::= 0
<REPTree_r> ::= REPTree <var_r> <mw-rep_r> <up_r>  <md-rep_r>
<mw-rep_r> ::= 2
<var_r> ::= RANDFLOAT(0.00001,0.1)
<up_r> ::= False
<md-rep_r> ::= -1
<DT_r> ::= DT <em_r> <uibk_r> <sm_r> <crv_r>
<em_r> ::= acc
<uibk_r> ::= False
<sm_r> ::= BestFirst
<crv_r> ::= 1
<JRip_r> ::= JRip <mtw_r> <cer_r> <up_r> <o_r>
<mtw_r> ::= RANDFLOAT(1.0,5.0)
<cer_r> ::= True
<o_r> ::= 2
<OneR_r> ::= OneR <mbs_r>
<mbs_r> ::= 6
<PART_r> ::= PART <PART-BASICS_r> <PART-CONSTRAINTS_r>
<PART-BASICS_r> ::= <mno_r> <bs_r>
<PART-CONSTRAINTS_r> ::= False
<KNN_r> ::= KNN <k_nn_r> <loo_r> <dw_r>
<k_nn_r> ::= 1
<loo_r> ::= False
<dw_r> ::= None
<KStar_r> ::= KStar <gb_r> <eab_r> <mm_r>
<gb_r> ::= 20
<eab_r> ::= False
<mm_r> ::= a
<VotedPerceptron_r> ::= VotedPerceptron <i_r> <mk_r> <e_r>
<i_r> ::= 1
<mk_r> ::= 10000
<e_r> ::= RANDFLOAT(0.2,5.0)
<MultiLayerPerc_r> ::= MultiLayerPerc <lr_r> <m_r> <nhn_r> <n2b_r> <reset_r> <decay_r>
<lr_r> ::= RANDFLOAT(0.1,1.0)
<m_r> ::= RANDFLOAT(0.0,1.0)
<nhn_r> ::= a
<n2b_r> ::= True
<reset_r> ::= True
<decay_r> ::= False
<StocGradDescent_r> ::= StocGradDescent <lf_r> <lr_sgd_r> <nn_r> <nrmv_r> <r_r>
<lf_r> ::= 0
<lr_sgd_r> ::= RANDFLOAT(0.00001,1.0)
<nn_r> ::= False
<nrmv_r> ::= False
<r_r> ::= RANDFLOAT(0.000000000001,10.0)
<LR_r> ::= LogisticRegression <r-lr_r>
<r-lr_r> ::=  RANDFLOAT(0.000000000001,10.0)
<SimpleLogistic_r> ::= SimpleLogistic <ucv_r> <uaic_r> <wtb_activate_r>
<ucv_r> ::= True
<SeqMinOptimization_r> ::= SeqMinOptimization <c_r> <ft_r> <bcm_r> <kernel_r>
<c_r> ::= RANDFLOAT(0.5,1.5) 
<ft_r> ::= 0
<bcm_r> ::= False
<kernel_r> ::= <poly_kern_r> <exp_r> <ulo_r>
<poly_kern_r> ::= PolyKernel
<exp_r> ::= RANDFLOAT(0.2,5.0)
<ulo_r> ::= True
<NB_r> ::= NaiveBayes <NB-Parameters_r>
<NB-Parameters_r> ::= None
<META-SLC_r> ::= <LWL_r> <ALG-WEIGHTED-TYPE_r> | RandomSubspace <sss_r> <ni_random_methods_r> <ALG-TYPE-WITHOUT-FS_r> | RandomCommittee <ni_random_methods_r> <ALG-TYPE_RC_r> | <Bagging_r> <ni_ada_and_bagging_r> <ALG-TYPE-WITHOUT-FS_r> | <AdaM1_r> <ni_ada_and_bagging_r> <ALG-WEIGHTED-TYPE_r> | <STACKING_r> | <VOTING_r>
<ALG-WEIGHTED-TYPE_r> ::= <J48_r> | DecisionStump | <RandomForest_r> | <RandomTree_r> | <REPTree_r> | <DT_r> | <JRip_r> | <PART_r> | ZeroR | <KNN_r> | <NB_r> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_r> |  <SeqMinOptimization_r> | <SimpleLogistic_r>
<LWL_r> ::= LWL <k_lwl_activate_r> <wk_activate_r>
<k_lwl_activate_r> ::= False
<k_lwl_r> ::= -1
<wk_activate_r> ::= False
<sss_r> ::= RANDFLOAT(0.1,1.0)
<ni_random_methods_r> ::= 10
<ALG-TYPE_RC_r> ::= <RandomForest_r> | <RandomTree_r> | <REPTree_r> | <StocGradDescent_r> | <MultiLayerPerc_r>
<Bagging_r> ::= BaggingSLC <BaggingSLC_BASICS_r>
<BaggingSLC_BASICS_r> ::= False <bsp-bagg_r>
<bsp-bagg_r> ::= 100
<AdaM1_r> ::= AdaM1 <wt_r> <ur_r>
<wt_r> ::= 100
<ni_ada_and_bagging_r> ::= 10
<ur_r> ::= False
<STACKING_r> ::= Stacking <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | Stacking <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | Stacking <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | Stacking <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r>
<VOTING_r> ::= <Vote_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | <Vote_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | <Vote_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> | <Vote_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r> <ALG-TYPE-WITHOUT-FS_r>
<Vote_r> ::= Vote <cr_r>
<cr_r> ::= AVG
<BRq_r> ::= BRq <dsr_r>
<CCq_r> ::= CCq <dsr_r>
<dsr_r> ::= RANDFLOAT(0.2,0.8)
<MCC_r> ::= MCC <chi_MCC_r> <ii_r> <eval_metrics_r>
<chi_MCC_r>::= 0
<ii_r> ::= 10
<eval_metrics_r> ::= Exact-match
<BCC_r> ::= BCC <dp_complete_r>
<dp_complete_r> ::= Ibf
<PMCC_r> ::= PMCC <B_r> <ts_r> <ii_r> <chi_PMCC_r> <ps_r> <eval_metrics_r>
<B_r> ::= RANDFLOAT(0.01,0.99)
<ts_r> ::= 0
<chi_PMCC_r> ::= 50
<ps_r> ::= 10
<CT_r> ::= CT <chi_CT_r> <w_r> <dp_r> <ii_r> <eval_metrics_r>
<chi_CT_r> ::= 0
<dp_r> ::= Ibf
<w_r> ::= -1 <d_r>
<d_r> ::= 1
<CDN_r> ::= CDN <i_cdn_cdt_r> <ci_r>
<i_cdn_cdt_r> ::= 1000
<ci_r> ::= 100
<CDT_r> ::= CDT <w_r> <dp-cdt_r> <i_cdn_cdt_r> <ci_r>
<dp-cdt_r> ::= None
<PS_r> ::= PS <sv_r> <pv_r>
<PSt_r> ::= PSt <sv_r> <pv_r>
<sv_r> ::= 0
<pv_r> ::= 0
<RAkELd_r> ::= RAkELd <les_r> <sv_r> <pv_r>
<RAkEL_r> ::= RAkEL <sre_r> <les_r> <sv_r> <pv_r>
<les_r> ::= 3
<sre_r> ::= 10
<ML-BPNN_r> ::= ML-BPNN <ne_r> <nhu_bpnn_r> <lr_bpnn_r> <m_bpnn_r>
<ne_r> ::= 100
<nhu_bpnn_r> ::= 10
<lr_bpnn_r> ::= RANDFLOAT(0.001,0.1) 
<m_bpnn_r> ::= RANDFLOAT(0.2,0.8)
<ML-DBPNN_r> ::= ML-DBPNN <ne_r> <nhu_bpnn_r> <lr_bpnn_r> <m_bpnn_r> <rbm_r>		
<rbm_r> ::= 2
<HOMER_r> ::= HOMER <t_r> <k_homer_r>
<t_r> ::= BalancedClustering
<k_homer_r> ::= 3
<META-MLC_r> ::= BR <ALGS-SLC_r> | CC <ALGS-SLC_r> | LP <ALGS-SLC_r>
<MBR_r> ::= MBR BR <ALGS-SLC_r>
<DEFINE-THRESHOLD-LEVEL_r> ::= threshold <predtshd_r>
<predtshd_r> ::=  RANDFLOAT(0.00000000000000000001,1.00)
