<START_i+r> ::= <DEFINE-THRESHOLD-LEVEL_i+r> <MLC-ALGORITHMS_i+r>
<MLC-ALGORITHMS_i+r> ::= BR <ALGS-SLC_i+r> | CC <ALGS-SLC_i+r> | LP <ALGS-SLC_i+r> | <BRq_i+r> <ALGS-SLC_i+r> | <CCq_i+r> <ALGS-SLC_i+r> | FW <ALGS-SLC_i+r> | RT <ALGS-SLC_i+r> | PCC <ALGS-SLC_i+r> | <CT_i+r> <ALGS-SLC_i+r>| <MCC_i+r> <ALGS-SLC_i+r>| <CDT_i+r> <ALGS-SLC_i+r> | <CDN_i+r> <ALGS-SLC_i+r> | <PS_i+r> <ALGS-SLC_i+r> | <PSt_i+r> <ALGS-SLC_i+r> | <RAkEL_i+r> <ALGS-SLC_i+r> | <RAkELd_i+r> <ALGS-SLC_i+r> | <BCC_i+r> <ALGS-SLC_i+r> | <PMCC_i+r> <ALGS-SLC_i+r> | <ML-BPNN_i+r> | <ML-DBPNN_i+r> <ML-BPNN_i+r> | <HOMER_i+r> <META-MLC_i+r> | <MBR_i+r>
<ALGS-SLC_i+r> ::= <ALGS-SLC-WITH-FS_i+r> | <ALG-TYPE-WITHOUT-FS_i+r> | <META-SLC_i+r>
<ALGS-SLC-WITH-FS_i+r> ::= <ASC_i+r> <ALG-TYPE-WITHOUT-FS_i+r>
<ASC_i+r> ::= ASC <sm_i+r>
<ALG-TYPE-WITHOUT-FS_i+r> ::= <J48_i+r> | DecisionStump |  <RandomForest_i+r> | <RandomTree_i+r> | <REPTree_i+r> | <DT_i+r> | <JRip_i+r> | <OneR_i+r> | <PART_i+r> | ZeroR | <KNN_i+r> | <KStar_i+r> | <VotedPerceptron_i+r> | <MultiLayerPerc_i+r> | <SeqMinOptimization_i+r> | <StocGradDescent_i+r> | <LR_i+r> | <NB_i+r> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_i+r> | <SimpleLogistic_i+r>
<J48_i+r> ::= J48 <J48-Complement_i+r> <J48-Basics_i+r>
<J48-Complement_i+r> ::= <cf_i+r> <sr_i+r>
<cf_i+r> ::= RANDFLOAT(0.0,1.0)
<sr_i+r> ::= True
<J48-Basics_i+r> ::= <mno_i+r> <ct_i+r> <bs_i+r> <umc_i+r> <ul_i+r>
<mno_i+r> ::= RANDINT_TYPE0(1,64)
<ct_i+r> ::= True
<bs_i+r> ::= False
<umc_i+r> ::= True
<ul_i+r> ::= False
<LogisticModelTrees_i+r> ::= LogisticModelTrees <mno-lmt_i+r> <cn_i+r> <sor_i+r> <fr_i+r> <eop_i+r> <uaic_i+r> <wtb_activate_i+r>
<mno-lmt_i+r> ::= RANDINT_TYPE0(1,64)
<cn_i+r> ::= False
<sor_i+r> ::= False
<fr_i+r> ::= True
<eop_i+r> ::= False
<wtb_activate_i+r> ::= False
<uaic_i+r> ::= False
<wtb_i+r> ::= RANDFLOAT(0.0,1.0)
<RandomForest_i+r> ::= RandomForest <nt_i+r> <nf_i+r>  <md_i+r>
<nt_i+r> ::= RANDINT_TYPE0(2,256)
<nf_i+r> ::= RANDINT_TYPE0(2,32)
<md_i+r> ::= RANDINT_TYPE0(2,20)
<RandomTree_i+r> ::= RandomTree <mw_i+r> <nfbgt_i+r> <nf_i+r>  <md_i+r>
<mw_i+r> ::= RANDINT_TYPE0(1,64)
<nfbgt_i+r> ::= <growing_the_tree_and_backfitting>
<growing_the_tree_and_backfitting> ::= RANDINT_TYPE0(0,5)
<REPTree_i+r> ::= REPTree <var_i+r> <mw-rep_i+r> <up_i+r>  <md-rep_i+r>
<mw-rep_i+r> ::= RANDINT_TYPE0(1,64)
<var_i+r> ::= RANDFLOAT(0.00001,0.1)
<up_i+r> ::= False
<md-rep_i+r> ::= RANDINT_TYPE0(0,20)
<DT_i+r> ::= DT <em_i+r> <uibk_i+r> <sm_i+r> <crv_i+r>
<em_i+r> ::= acc
<uibk_i+r> ::= False
<sm_i+r> ::= BestFirst
<crv_i+r> ::= 1 | 2 | 3 | 4 
<JRip_i+r> ::= JRip <mtw_i+r> <cer_i+r> <up_i+r> <o_i+r>
<mtw_i+r> ::= RANDFLOAT(1.0,5.0)
<cer_i+r> ::= True
<o_i+r> ::= RANDINT_TYPE0(1,5) 
<OneR_i+r> ::= OneR <mbs_i+r>
<mbs_i+r> ::= RANDINT_TYPE0(1,32)
<PART_i+r> ::= PART <PART-BASICS_i+r> <PART-CONSTRAINTS_i+r>
<PART-BASICS_i+r> ::= <mno_i+r> <bs_i+r>
<PART-CONSTRAINTS_i+r> ::= False
<KNN_i+r> ::= KNN <k_nn_i+r> <loo_i+r> <dw_i+r>
<k_nn_i+r> ::= RANDINT_TYPE0(1,64)
<loo_i+r> ::= False
<dw_i+r> ::= None
<KStar_i+r> ::= KStar <gb_i+r> <eab_i+r> <mm_i+r>
<gb_i+r> ::= RANDINT_TYPE0(1,100)
<eab_i+r> ::= False
<mm_i+r> ::= a
<VotedPerceptron_i+r> ::= VotedPerceptron <i_i+r> <mk_i+r> <e_i+r>
<i_i+r> ::= RANDINT_TYPE0(1,10)
<mk_i+r> ::= RANDINT_TYPE0(5000,50000)
<e_i+r> ::= RANDFLOAT(0.2,5.0)
<MultiLayerPerc_i+r> ::= MultiLayerPerc <lr_i+r> <m_i+r> <nhn_i+r> <n2b_i+r> <reset_i+r> <decay_i+r>
<lr_i+r> ::= RANDFLOAT(0.1,1.0)
<m_i+r> ::= RANDFLOAT(0.0,1.0)
<nhn_i+r> ::= a
<n2b_i+r> ::= True
<reset_i+r> ::= True
<decay_i+r> ::= False
<StocGradDescent_i+r> ::= StocGradDescent <lf_i+r> <lr_sgd_i+r> <nn_i+r> <nrmv_i+r> <r_i+r>
<lf_i+r> ::= 0
<lr_sgd_i+r> ::= RANDFLOAT(0.00001,1.0)
<nn_i+r> ::= False
<nrmv_i+r> ::= False
<r_i+r> ::= RANDFLOAT(0.000000000001,10.0)
<LR_i+r> ::= LogisticRegression <r-lr_i+r>
<r-lr_i+r> ::= RANDFLOAT(0.000000000001,10.0)
<SimpleLogistic_i+r> ::= SimpleLogistic <ucv_i+r> <uaic_i+r> <wtb_activate_i+r>
<ucv_i+r> ::= True
<SeqMinOptimization_i+r> ::= SeqMinOptimization <c_i+r> <ft_i+r> <bcm_i+r> <kernel_i+r>
<c_i+r> ::=  RANDFLOAT(0.5,1.5) 
<ft_i+r> ::= 0
<bcm_i+r> ::= False
<kernel_i+r> ::= <poly_kern_i+r> <exp_i+r> <ulo_i+r>
<poly_kern_i+r> ::= PolyKernel
<exp_i+r> ::= RANDFLOAT(0.2,5.0)
<ulo_i+r> ::= True
<NB_i+r> ::= NaiveBayes <NB-Parameters_i+r>
<NB-Parameters_i+r> ::= None
<META-SLC_i+r> ::= <LWL_i+r> <ALG-WEIGHTED-TYPE_i+r> | RandomSubspace <sss_i+r> <ni_random_methods_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | RandomCommittee <ni_random_methods_i+r> <ALG-TYPE_RC_i+r> | <Bagging_i+r> <ni_ada_and_bagging_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | <AdaM1_i+r> <ni_ada_and_bagging_i+r> <ALG-WEIGHTED-TYPE_i+r> | <STACKING_i+r> | <VOTING_i+r>
<ALG-WEIGHTED-TYPE_i+r> ::= <J48_i+r> | DecisionStump | <RandomForest_i+r> | <RandomTree_i+r> | <REPTree_i+r> | <DT_i+r> | <JRip_i+r> | <PART_i+r> | ZeroR | <KNN_i+r> | <NB_i+r> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_i+r> |  <SeqMinOptimization_i+r> | <SimpleLogistic_i+r>
<LWL_i+r> ::= LWL <k_lwl_activate_i+r> <wk_activate_i+r>
<k_lwl_activate_i+r> ::= False
<k_lwl_i+r> ::= -1 | 10 | 30 | 60 | 90 | 120
<wk_activate_i+r> ::= False
<sss_i+r> ::= RANDFLOAT(0.1,1.0)
<ni_random_methods_i+r> ::= RANDINT_TYPE0(2,64)
<ALG-TYPE_RC_i+r> ::= <RandomForest_i+r> | <RandomTree_i+r> | <REPTree_i+r> | <StocGradDescent_i+r> | <MultiLayerPerc_i+r>
<Bagging_i+r> ::= BaggingSLC <BaggingSLC_BASICS_i+r>
<BaggingSLC_BASICS_i+r> ::= False <bsp-bagg_i+r>
<bsp-bagg_i+r> ::= RANDINT_TYPE0(10,100)
<AdaM1_i+r> ::= AdaM1 <wt_i+r> <ur_i+r>
<wt_i+r> ::= RANDINT_TYPE0(50,100) 
<ni_ada_and_bagging_i+r> ::= RANDINT_TYPE0(2,128)
<ur_i+r> ::= False
<STACKING_i+r> ::= Stacking <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | Stacking <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | Stacking <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | Stacking <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r>
<VOTING_i+r> ::= <Vote_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | <Vote_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | <Vote_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> | <Vote_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r> <ALG-TYPE-WITHOUT-FS_i+r>
<Vote_i+r> ::= Vote <cr_i+r>
<cr_i+r> ::= AVG
<BRq_i+r> ::= BRq <dsr_i+r>
<CCq_i+r> ::= CCq <dsr_i+r>
<dsr_i+r> ::= RANDFLOAT(0.2,0.8)
<MCC_i+r> ::= MCC <chi_MCC_i+r> <ii_i+r> <eval_metrics_i+r>
<chi_MCC_i+r>::= RANDINT_TYPE0(2,1500)
<ii_i+r> ::= RANDINT_TYPE0(2,100)
<eval_metrics_i+r> ::= Exact-match
<BCC_i+r> ::= BCC <dp_complete_i+r>
<dp_complete_i+r> ::= Ibf
<PMCC_i+r> ::= PMCC <B_i+r> <ts_i+r> <ii_i+r> <chi_PMCC_i+r> <ps_i+r> <eval_metrics_i+r>
<B_i+r> ::= RANDFLOAT(0.01,0.99)
<ts_i+r> ::= 0
<chi_PMCC_i+r> ::= RANDINT_TYPE0(51,1500)
<ps_i+r> ::= RANDINT_TYPE0(1,50)
<CT_i+r> ::= CT <chi_CT_i+r> <w_i+r> <dp_i+r> <ii_i+r> <eval_metrics_i+r>
<chi_CT_i+r> ::= RANDINT_TYPE0(2,1500)
<dp_i+r> ::= Ibf
<w_i+r> ::= 0 1 | -1 <d_i+r>
<d_i+r> ::= RANDINT_TYPE1(1,SQRT(L)+1)
<CDN_i+r> ::= CDN <i_cdn_cdt_i+r> <ci_i+r>
<i_cdn_cdt_i+r> ::= RANDINT_TYPE0(101,1000)
<ci_i+r> ::= RANDINT_TYPE0(1,100)
<CDT_i+r> ::= CDT <w_i+r> <dp-cdt_i+r> <i_cdn_cdt_i+r> <ci_i+r>
<dp-cdt_i+r> ::= None
<PS_i+r> ::= PS <sv_i+r> <pv_i+r>
<PSt_i+r> ::= PSt <sv_i+r> <pv_i+r>
<sv_i+r> ::= RANDINT_TYPE0(0,5)
<pv_i+r> ::= RANDINT_TYPE0(1,5) 
<RAkELd_i+r> ::= RAkELd <les_i+r> <sv_i+r> <pv_i+r>
<RAkEL_i+r> ::= RAkEL <sre_i+r> <les_i+r> <sv_i+r> <pv_i+r>
<les_i+r> ::= RANDINT_TYPE2(1,L/2)
<sre_i+r> ::= RANDINT_TYPE3(2,min(2L;100))
<ML-BPNN_i+r> ::= ML-BPNN <ne_i+r> <nhu_bpnn_i+r> <lr_bpnn_i+r> <m_bpnn_i+r>
<ne_i+r> ::= RANDINT_TYPE0(10,1000)
<nhu_bpnn_i+r> ::=  RANDINT_TYPE4((0.2,1.0)*n_attributes)
<lr_bpnn_i+r> ::= RANDFLOAT(0.001,0.1) 
<m_bpnn_i+r> ::=  RANDFLOAT(0.2,0.8)
<ML-DBPNN_i+r> ::= ML-DBPNN <ne_i+r> <nhu_bpnn_i+r> <lr_bpnn_i+r> <m_bpnn_i+r> <rbm_i+r>		
<rbm_i+r> ::= RANDINT_TYPE0(2,5)
<HOMER_i+r> ::= HOMER <t_i+r> <k_homer_i+r>
<t_i+r> ::= BalancedClustering
<k_homer_i+r> ::= RANDINT_TYPE6(2,L-1)
<META-MLC_i+r> ::= BR <ALGS-SLC_i+r> | CC <ALGS-SLC_i+r> | LP <ALGS-SLC_i+r>
<MBR_i+r> ::= MBR BR <ALGS-SLC_i+r>
<DEFINE-THRESHOLD-LEVEL_i+r> ::= threshold <predtshd_i+r>
<predtshd_i+r> ::= RANDFLOAT(0.00000000000000000001,1.00)
