<START_c> ::= <DEFINE-THRESHOLD-LEVEL_c> <MLC-ALGORITHMS_c>
<MLC-ALGORITHMS_c> ::= BR <ALGS-SLC_c> | CC <ALGS-SLC_c> | LP <ALGS-SLC_c> | <BRq_c> <ALGS-SLC_c> | <CCq_c> <ALGS-SLC_c> | FW <ALGS-SLC_c> | RT <ALGS-SLC_c> | PCC <ALGS-SLC_c> | <CT_c> <ALGS-SLC_c>| <MCC_c> <ALGS-SLC_c>| <CDT_c> <ALGS-SLC_c> | <CDN_c> <ALGS-SLC_c> | <PS_c> <ALGS-SLC_c> | <PSt_c> <ALGS-SLC_c> | <RAkEL_c> <ALGS-SLC_c> | <RAkELd_c> <ALGS-SLC_c> | <BCC_c> <ALGS-SLC_c> | <PMCC_c> <ALGS-SLC_c> | <ML-BPNN_c> | <ML-DBPNN_c> <ML-BPNN_c> |  <HOMER_c> <META-MLC_c> | <MBR_c>
<ALGS-SLC_c> ::= <ALGS-SLC-WITH-FS_c> | <ALG-TYPE-WITHOUT-FS_c> | <META-SLC_c>
<ALGS-SLC-WITH-FS_c> ::= <ASC_c> <ALG-TYPE-WITHOUT-FS_c>
<ASC_c> ::= ASC <sm_c>
<ALG-TYPE-WITHOUT-FS_c> ::= <J48_c> | DecisionStump |  <RandomForest_c> | <RandomTree_c> | <REPTree_c> | <DT_c> | <JRip_c> | <OneR_c> | <PART_c> | ZeroR | <KNN_c> | <KStar_c> | <VotedPerceptron_c> | <MultiLayerPerc_c> | <SeqMinOptimization_c> | <StocGradDescent_c> | <LR_c> | <NB_c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_c> | <SimpleLogistic_c>
<J48_c> ::= J48 <J48-Complement_c> <J48-Basics_c>
<J48-Complement_c> ::= <cf_c> <sr_c> | True
<cf_c> ::= 0.25
<sr_c> ::= True | False
<J48-Basics_c> ::= <mno_c> <ct_c> <bs_c> <umc_c> <ul_c>
<mno_c> ::= 2
<ct_c> ::= True | False
<bs_c> ::= True | False
<umc_c> ::= True | False
<ul_c> ::= True | False
<RandomForest_c> ::= RandomForest <nt_c> <nf_c>  <md-rep_c>
<md-rep_c> ::= -1
<nt_c> ::= 100
<nf_c> ::= 0
<md_c> ::= 0
<RandomTree_c> ::= RandomTree <mw_c> <nfbgt_c> <nf_c>  <md_c>
<mw_c> ::= 1
<nfbgt_c> ::= <growing_the_tree_and_backfitting_c>
<growing_the_tree_and_backfitting_c> ::= 0
<REPTree_c> ::= REPTree <var_c> <mw-rep_c> <up_c>  <md_c>
<mw-rep_c> ::= 2
<var_c> ::= 0.001
<up_c> ::= True | False
<DT_c> ::= DT <em_c> <uibk_c> <sm_c> <crv_c> 
<em_c> ::= acc | rmse | mae | auc
<uibk_c> ::= True | False
<sm_c> ::= GreedyStepwise | BestFirst
<crv_c> ::= 1
<JRip_c> ::= JRip <mtw_c> <cer_c> <up_c> <o_c> 
<mtw_c> ::= 2.0
<cer_c> ::= True | False
<o_c> ::= 2
<OneR_c> ::= OneR <mbs_c>
<mbs_c> ::= 6
<PART_c> ::= PART <PART-BASICS_c> <PART-CONSTRAINTS_c>
<PART-BASICS_c> ::= <mno_c> <bs_c>
<PART-CONSTRAINTS_c> ::= True <nr_c> | False
<nr_c> ::= 3
<KNN_c> ::= KNN <k_nn_c> <loo_c> <dw_c>
<k_nn_c> ::= 1
<loo_c> ::= True | False
<dw_c> ::= F | I | None
<KStar_c> ::= KStar <gb_c> <eab_c> <mm_c>
<gb_c> ::= 20
<eab_c> ::= True | False
<mm_c> ::= a | d | m | n
<VotedPerceptron_c> ::= VotedPerceptron <i_c> <mk_c> <e_c>
<i_c> ::= 1
<mk_c> ::= 10000
<e_c> ::=  1.0
<MultiLayerPerc_c> ::= MultiLayerPerc <lr_c> <m_c> <nhn_c> <n2b_c> <reset_c> <decay_c>
<lr_c> ::= 0.3
<m_c> ::= 0.2
<nhn_c> ::= a | i | o | t
<n2b_c> ::= True | False
<reset_c> ::= True | False
<decay_c> ::= True | False
<LR_c> ::= LogisticRegression <r-lr_c>
<r-lr_c> ::= 0.00000001
<StocGradDescent_c> ::= StocGradDescent <lf_c> <lr_sgd_c> <nn_c> <nrmv_c> <r_c>
<lf_c> ::= 0 | 1 | 2
<lr_sgd_c> ::= 0.01
<nn_c> ::= True | False
<nrmv_c> ::= True | False
<r_c> ::=  0.0001
<SeqMinOptimization_c> ::= SeqMinOptimization <c_c> <ft_c> <bcm_c> <kernel_c>
<c_c> ::= 1.0
<ft_c> ::= 0 | 1 | 2
<bcm_c> ::= True | False
<kernel_c> ::= <poly_kern_c> <exp_c> <ulo_c> | Puk <om_c> <sig_c> | RBFKernel <g_c>
<poly_kern_c> ::= NormalizedPolyKernel | PolyKernel
<exp_c> ::= 1.0
<ulo_c> ::= True | False
<om_c> ::= 1.0
<sig_c> ::= 1.0
<g_c> ::= 0.01
<NB_c> ::= NaiveBayes <NB-Parameters_c>
<NB-Parameters_c> ::= uke | usd | None
<SimpleLogistic_c> ::= SimpleLogistic <ucv_c> <uaic_c> <wtb_activate_c>
<ucv_c> ::= True | False
<LogisticModelTrees_c> ::= LogisticModelTrees <mno-lmt_c> <cn_c> <sor_c> <fr_c> <eop_c> <uaic_c> <wtb_activate_c>
<mno-lmt_c> ::= 15
<cn_c> ::= True | False
<sor_c> ::= True | False
<fr_c> ::= True | False
<eop_c> ::= True | False
<wtb_activate_c> ::= True <wtb_c> | False
<uaic_c> ::= True | False
<wtb_c> ::= 0.0
<META-SLC_c> ::= <LWL_c> <ALG-WEIGHTED-TYPE_c> | RandomSubspace <sss_c> <ni_random_methods_c> <ALG-TYPE-WITHOUT-FS_c> | RandomCommittee <ni_random_methods_c> <ALG-TYPE_RC_c> | <Bagging_c> <ni_ada_and_bagging_c> <ALG-TYPE-WITHOUT-FS_c> | <AdaM1_c> <ni_ada_and_bagging_c> <ALG-WEIGHTED-TYPE_c> | <STACKING_c> | <VOTING_c>
<ALG-WEIGHTED-TYPE_c> ::= <J48_c> | DecisionStump | <RandomForest_c> | <RandomTree_c> | <REPTree_c> | <DT_c> | <JRip_c> | <PART_c> | ZeroR | <KNN_c> | <NB_c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_c> |  <SeqMinOptimization_c> | <SimpleLogistic_c>
<LWL_c> ::= LWL <k_lwl_activate_c> <wk_activate_c>
<k_lwl_activate_c> ::= True <k_lwl_c> | False
<k_lwl_c> ::= -1
<wk_activate_c> ::= True <wk_c> | False
<wk_c> ::= 0 | 1 | 2 | 3 | 4
<sss_c> ::=  0.5
<ni_random_methods_c> ::= 10
<ALG-TYPE_RC_c> ::= <RandomForest_c> | <RandomTree_c> | <REPTree_c> | <StocGradDescent_c> | <MultiLayerPerc_c>
<Bagging_c> ::= BaggingSLC <BaggingSLC_BASICS_c>
<BaggingSLC_BASICS_c> ::= False <bsp-bagg_c> | True 100
<bsp-bagg_c> ::= 100
<AdaM1_c> ::= AdaM1 <wt_c> <ur_c>
<wt_c> ::= 100
<ni_ada_and_bagging_c> ::= 10
<ur_c> ::= True | False
<STACKING_c> ::= Stacking <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | Stacking <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | Stacking <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | Stacking <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c>
<VOTING_c> ::= <Vote_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | <Vote_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | <Vote_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> | <Vote_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c> <ALG-TYPE-WITHOUT-FS_c>
<Vote_c> ::= Vote <cr_c>
<cr_c> ::= AVG | PROD | MAJ | MIN | MAX
<BRq_c> ::= BRq <dsr_c>
<CCq_c> ::= CCq <dsr_c>
<dsr_c> ::= 0.75
<MCC_c> ::= MCC <chi_MCC_c> <ii_c> <eval_metrics_c>
<CDN_c> ::= CDN <i_cdn_cdt_c> <ci_c>
<chi_MCC_c>::= <chi_CT_c>
<ii_c> ::= 10
<eval_metrics_c> ::= Accuracy | Jaccard-index | Hamming-score | Exact-match | Jaccard-distance | Hamming-loss | ZeroOne-loss | Harmonic-score | One-error | Rank-loss | Avg-precision | Log-Loss-lim:L | Log-Loss-lim:D | Micro-Precision | Micro-Recall | Macro-Precision | Macro-Recall | F1-micro-averaged | F1-macro-averaged-by-example | F1-macro-averaged-by-label | AUPRC-macro-averaged | AUROC-macro-averaged | Levenshtein-distance
<CT_c> ::= CT <chi_CT_c> <w_c> <dp_c> <ii_c> <eval_metrics_c>
<chi_CT_c> ::= 10
<dp_c> ::= C | I | Ib | Ibf | H | Hbf | X | F | None
<w_c> ::= 0 1 | -1 <d_c>
<d_c> ::= 1
<CDT_c> ::= CDT <w_c> <dp_c> <i_cdn_cdt_c> <ci_c>
<i_cdn_cdt_c> ::= 1000
<ci_c> ::= 100
<PS_c> ::= PS <sv_c> <pv_c>
<PSt_c> ::= PSt <sv_c> <pv_c>
<RAkELd_c> ::= RAkELd <les_c> <sv_c> <pv_c>
<RAkEL_c> ::= RAkEL <sre_c> <les_c> <sv_c> <pv_c>
<sv_c> ::= 0
<pv_c> ::= 0
<les_c> ::= 3
<sre_c> ::= 10
<BCC_c> ::= BCC <dp_complete_c>
<dp_complete_c> ::= L | <dp_c>
<B_c> ::= 0.03
<ts_c> ::= 0 | 1
<chi_PMCC_c> ::= 50
<ps_c> ::= 10
<PMCC_c> ::= PMCC <B_c> <ts_c> <ii_c> <chi_PMCC_c> <ps_c> <eval_metrics_c>
<ML-BPNN_c> ::= ML-BPNN <ne_c> <nhu_bpnn_c> <lr_bpnn_c> <m_bpnn_c>
<ne_c> ::= 100
<nhu_bpnn_c> ::= 10
<lr_bpnn_c> ::= 0.1
<m_bpnn_c> ::= 0.1
<ML-DBPNN_c> ::= ML-DBPNN <ne_c> <nhu_bpnn_c> <lr_bpnn_c> <m_bpnn_c> <rbm_c>		
<rbm_c> ::= 2
<HOMER_c> ::= HOMER <t_c> <k_homer_c>
<t_c> ::= BalancedClustering | Clustering | Random
<k_homer_c> ::= 3
<META-MLC_c> ::= BR <ALGS-SLC_c> | CC <ALGS-SLC_c> | LP <ALGS-SLC_c>
<MBR_c> ::= MBR BR <<ALGS-SLC_c>
<DEFINE-THRESHOLD-LEVEL_c> ::= threshold <predtshd_c>
<predtshd_c> ::= PCut1 | PCutL |  0.5
