<START_r+c> ::= <DEFINE-THRESHOLD-LEVEL_r+c> <MLC-ALGORITHMS_r+c>
<MLC-ALGORITHMS_r+c> ::= BR <ALGS-SLC_r+c> | CC <ALGS-SLC_r+c> | LP <ALGS-SLC_r+c> | <BRq_r+c> <ALGS-SLC_r+c> | <CCq_r+c> <ALGS-SLC_r+c> | FW <ALGS-SLC_r+c> | RT <ALGS-SLC_r+c> | PCC <ALGS-SLC_r+c> | <CT_r+c> <ALGS-SLC_r+c>| <MCC_r+c> <ALGS-SLC_r+c>| <CDT_r+c> <ALGS-SLC_r+c> | <CDN_r+c> <ALGS-SLC_r+c> | <PS_r+c> <ALGS-SLC_r+c> | <PSt_r+c> <ALGS-SLC_r+c> | <RAkEL_r+c> <ALGS-SLC_r+c> | <RAkELd_r+c> <ALGS-SLC_r+c> | <BCC_r+c> <ALGS-SLC_r+c> | <PMCC_r+c> <ALGS-SLC_r+c> | <ML-BPNN_r+c> | <ML-DBPNN_r+c> <ML-BPNN_r+c> |  <HOMER_r+c> <META-MLC_r+c> | <MBR_r+c>
<ALGS-SLC_r+c> ::= <ALGS-SLC-WITH-FS_r+c> | <ALG-TYPE-WITHOUT-FS_r+c> | <META-SLC_r+c>
<ALGS-SLC-WITH-FS_r+c> ::= <ASC_r+c> <ALG-TYPE-WITHOUT-FS_r+c>
<ASC_r+c> ::= ASC <sm_r+c>
<ALG-TYPE-WITHOUT-FS_r+c> ::= <J48_r+c> | DecisionStump |  <RandomForest_r+c> | <RandomTree_r+c> | <REPTree_r+c> | <DT_r+c> | <JRip_r+c> | <OneR_r+c> | <PART_r+c> | ZeroR | <KNN_r+c> | <KStar_r+c> | <VotedPerceptron_r+c> | <MultiLayerPerc_r+c> | <SeqMinOptimization_r+c> | <StocGradDescent_r+c> | <LR_r+c> | <NB_r+c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_r+c> | <SimpleLogistic_r+c>
<J48_r+c> ::= J48 <J48-Complement_r+c> <J48-Basics_r+c>
<J48-Complement_r+c> ::= <cf_r+c> <sr_r+c> | True
<cf_r+c> ::= RANDFLOAT(0.0,1.0)
<sr_r+c> ::= True | False
<J48-Basics_r+c> ::= <mno_r+c> <ct_r+c> <bs_r+c> <umc_r+c> <ul_r+c>
<mno_r+c> ::= 2
<ct_r+c> ::= True | False
<bs_r+c> ::= True | False
<umc_r+c> ::= True | False
<ul_r+c> ::= True | False
<RandomForest_r+c> ::= RandomForest <nt_r+c> <nf_r+c>  <md-rep_r+c>
<md-rep_r+c> ::= -1
<nt_r+c> ::= 100
<nf_r+c> ::= 0
<md_r+c> ::= 0
<RandomTree_r+c> ::= RandomTree <mw_r+c> <nfbgt_r+c> <nf_r+c>  <md_r+c>
<mw_r+c> ::= 1
<nfbgt_r+c> ::= <growing_the_tree_and_backfitting_r+c>
<growing_the_tree_and_backfitting_r+c> ::= 0
<REPTree_r+c> ::= REPTree <var_r+c> <mw-rep_r+c> <up_r+c>  <md_r+c>
<mw-rep_c> ::= 2
<var_r+c> ::= RANDFLOAT(0.00001,0.1)
<up_r+c> ::= True | False
<DT_r+c> ::= DT <em_r+c> <uibk_r+c> <sm_r+c> <crv_r+c> 
<em_r+c> ::= acc | rmse | mae | auc
<uibk_r+c> ::= True | False
<sm_r+c> ::= GreedyStepwise | BestFirst
<crv_r+c> ::= 1
<JRip_r+c> ::= JRip <mtw_r+c> <cer_r+c> <up_r+c> <o_r+c> 
<mtw_r+c> ::= RANDFLOAT(1.0,5.0)
<cer_r+c> ::= True | False
<o_r+c> ::= 2
<OneR_r+c> ::= OneR <mbs_r+c>
<mbs_r+c> ::= 6
<PART_r+c> ::= PART <PART-BASICS_r+c> <PART-CONSTRAINTS_r+c>
<PART-BASICS_r+c> ::= <mno_r+c> <bs_r+c>
<PART-CONSTRAINTS_r+c> ::= True <nr_r+c> | False
<nr_r+c> ::= 3
<KNN_r+c> ::= KNN <k_nn_r+c> <loo_r+c> <dw_r+c>
<k_nn_r+c> ::= 1
<loo_r+c> ::= True | False
<dw_r+c> ::= F | I | None
<KStar_r+c> ::= KStar <gb_r+c> <eab_r+c> <mm_r+c>
<gb_r+c> ::= 20
<eab_r+c> ::= True | False
<mm_r+c> ::= a | d | m | n
<VotedPerceptron_r+c> ::= VotedPerceptron <i_r+c> <mk_r+c> <e_r+c>
<i_r+c> ::= 1
<mk_r+c> ::= 10000
<e_r+c> ::= RANDFLOAT(0.2,5.0)
<MultiLayerPerc_r+c> ::= MultiLayerPerc <lr_r+c> <m_r+c> <nhn_r+c> <n2b_r+c> <reset_r+c> <decay_r+c>
<lr_r+c> ::= RANDFLOAT(0.1,1.0)
<m_r+c> ::= RANDFLOAT(0.0,1.0)
<nhn_r+c> ::= a | i | o | t
<n2b_r+c> ::= True | False
<reset_r+c> ::= True | False
<decay_r+c> ::= True | False
<LR_r+c> ::= LogisticRegression <r_r+c>
<StocGradDescent_r+c> ::= StocGradDescent <lf_r+c> <lr_sgd_r+c> <nn_r+c> <nrmv_r+c> <r_r+c>
<lf_r+c> ::= 0 | 1 | 2
<lr_sgd_r+c> ::= RANDFLOAT(0.00001,1.0)
<nn_r+c> ::= True | False
<nrmv_r+c> ::= True | False
<r_r+c> ::= RANDFLOAT(0.000000000001,10.0)
<SeqMinOptimization_r+c> ::= SeqMinOptimization <c_r+c> <ft_r+c> <bcm_r+c> <kernel_r+c>
<c_r+c> ::= RANDFLOAT(0.5,1.5)
<ft_r+c> ::= 0 | 1 | 2
<bcm_r+c> ::= True | False
<kernel_r+c> ::= <poly_kern_r+c> <exp_r+c> <ulo_r+c> | Puk <om_r+c> <sig_r+c> | RBFKernel <g_r+c>
<poly_kern_r+c> ::= NormalizedPolyKernel | PolyKernel
<exp_r+c> ::= RANDFLOAT(0.2,5.0)
<ulo_r+c> ::= True | False
<om_r+c> ::= RANDFLOAT(0.1,1.0)
<sig_r+c> ::= RANDFLOAT(0.1,10.0)
<g_r+c> ::= RANDFLOAT(0.0001,1.0)
<NB_r+c> ::= NaiveBayes <NB-Parameters_r+c>
<NB-Parameters_r+c> ::= uke | usd | None
<SimpleLogistic_r+c> ::= SimpleLogistic <ucv_r+c> <uaic_r+c> <wtb_activate_r+c>
<ucv_r+c> ::= True | False
<LogisticModelTrees_r+c> ::= LogisticModelTrees <mno-lmt_r+c> <cn_r+c> <sor_r+c> <fr_r+c> <eop_r+c> <uaic_r+c> <wtb_activate_r+c>
<mno-lmt_r+c> ::= 15
<cn_r+c> ::= True | False
<sor_r+c> ::= True | False
<fr_r+c> ::= True | False
<eop_r+c> ::= True | False
<wtb_activate_r+c> ::= True <wtb_r+c> | False
<uaic_r+c> ::= True | False
<wtb_r+c> ::= RANDFLOAT(0.0,1.0)
<META-SLC_r+c> ::= <LWL_r+c> <ALG-WEIGHTED-TYPE_r+c> | RandomSubspace <sss_r+c> <ni_random_methods_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | RandomCommittee <ni_random_methods_r+c> <ALG-TYPE_RC_r+c> | <Bagging_r+c> <ni_ada_and_bagging_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | <AdaM1_r+c> <ni_ada_and_bagging_r+c> <ALG-WEIGHTED-TYPE_r+c> | <STACKING_r+c> | <VOTING_r+c>
<ALG-WEIGHTED-TYPE_r+c> ::= <J48_r+c> | DecisionStump | <RandomForest_r+c> | <RandomTree_r+c> | <REPTree_r+c> | <DT_r+c> | <JRip_r+c> | <PART_r+c> | ZeroR | <KNN_r+c> | <NB_r+c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_r+c> |  <SeqMinOptimization_r+c> | <SimpleLogistic_r+c>
<LWL_r+c> ::= LWL <k_lwl_activate_r+c> <wk_activate_r+c>
<k_lwl_activate_r+c> ::= True <k_lwl_r+c> | False
<k_lwl_r+c> ::= -1
<wk_activate_r+c> ::= True <wk_r+c> | False
<wk_r+c> ::= 0 | 1 | 2 | 3 | 4
<sss_r+c> ::= RANDFLOAT(0.1,1.0)
<ni_random_methods_r+c> ::= 10
<ALG-TYPE_RC_r+c> ::= <RandomForest_r+c> | <RandomTree_r+c> | <REPTree_r+c> | <StocGradDescent_r+c> | <MultiLayerPerc_r+c>
<Bagging_r+c> ::= BaggingSLC <BaggingSLC_BASICS_r+c>
<BaggingSLC_BASICS_r+c> ::= False <bsp-bagg_r+c> | True 100
<bsp-bagg_r+c> ::= 100
<AdaM1_r+c> ::= AdaM1 <wt_r+c> <ur_r+c>
<wt_r+c> ::= 100
<ni_ada_and_bagging_r+c> ::= 10
<ur_r+c> ::= True | False
<STACKING_r+c> ::= Stacking <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | Stacking <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | Stacking <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | Stacking <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c>
<VOTING_r+c> ::= <Vote_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | <Vote_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | <Vote_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> | <Vote_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c> <ALG-TYPE-WITHOUT-FS_r+c>
<Vote_r+c> ::= Vote <cr_r+c>
<cr_r+c> ::= AVG | PROD | MAJ | MIN | MAX
<BRq_r+c> ::= BRq <dsr_r+c>
<CCq_r+c> ::= CCq <dsr_r+c>
<dsr_r+c> ::= RANDFLOAT(0.2,0.8)
<MCC_r+c> ::= MCC <chi_MCC_r+c> <ii_r+c> <eval_metrics_r+c>
<CDN_r+c> ::= CDN <i_cdn_cdt_r+c> <ci_r+c>
<chi_MCC_r+c>::= <chi_CT_r+c>
<ii_r+c> ::= 10
<eval_metrics_r+c> ::= Accuracy | Jaccard-index | Hamming-score | Exact-match | Jaccard-distance | Hamming-loss | ZeroOne-loss | Harmonic-score | One-error | Rank-loss | Avg-precision | Log-Loss-lim:L | Log-Loss-lim:D | Micro-Precision | Micro-Recall | Macro-Precision | Macro-Recall | F1-micro-averaged | F1-macro-averaged-by-example | F1-macro-averaged-by-label | AUPRC-macro-averaged | AUROC-macro-averaged | Levenshtein-distance
<CT_r+c> ::= CT <chi_CT_r+c> <w_r+c> <dp_r+c> <ii_r+c> <eval_metrics_r+c>
<chi_CT_r+c> ::= 10
<dp_r+c> ::= C | I | Ib | Ibf | H | Hbf | X | F | None
<w_r+c> ::= 0 1 | -1 <d_r+c>
<d_r+c> ::= 1
<CDT_r+c> ::= CDT <w_r+c> <dp_r+c> <i_cdn_cdt_r+c> <ci_r+c>
<i_cdn_cdt_r+c> ::= 1000
<ci_r+c> ::= 100
<PS_r+c> ::= PS <sv_r+c> <pv_r+c>
<PSt_r+c> ::= PSt <sv_r+c> <pv_r+c>
<RAkELd_r+c> ::= RAkELd <les_r+c> <sv_r+c> <pv_r+c>
<RAkEL_r+c> ::= RAkEL <sre_r+c> <les_r+c> <sv_r+c> <pv_r+c>
<sv_r+c> ::= 0
<pv_r+c> ::= 0
<les_r+c> ::= 3
<sre_r+c> ::= 10
<BCC_r+c> ::= BCC <dp_complete_r+c>
<dp_complete_r+c> ::= L | <dp_r+c>
<B_r+c> ::= RANDFLOAT(0.01,0.99)
<ts_r+c> ::= 0 | 1
<chi_PMCC_r+c> ::= 50
<ps_r+c> ::= 10
<PMCC_r+c> ::= PMCC <B_r+c> <ts_r+c> <ii_r+c> <chi_PMCC_r+c> <ps_r+c> <eval_metrics_r+c>
<ML-BPNN_r+c> ::= ML-BPNN <ne_r+c> <nhu_bpnn_r+c> <lr_bpnn_r+c> <m_bpnn_r+c>
<ne_r+c> ::= 100
<nhu_bpnn_r+c> ::= 10
<lr_bpnn_r+c> ::= RANDFLOAT(0.001,0.1)
<m_bpnn_r+c> ::=  RANDFLOAT(0.2,0.8)
<ML-DBPNN_r+c> ::= ML-DBPNN <ne_r+c> <nhu_bpnn_r+c> <lr_bpnn_r+c> <m_bpnn_r+c> <rbm_r+c>		
<rbm_r+c> ::= 2
<HOMER_r+c> ::= HOMER <t_r+c> <k_homer_r+c>
<t_r+c> ::= BalancedClustering | Clustering | Random
<k_homer_r+c> ::= 3
<META-MLC_r+c> ::= BR <ALGS-SLC_r+c> | CC <ALGS-SLC_r+c> | LP <ALGS-SLC_r+c>
<MBR_r+c> ::= MBR BR <<ALGS-SLC_r+c>
<DEFINE-THRESHOLD-LEVEL_r+c> ::= threshold <predtshd_r+c>
<predtshd_r+c> ::= PCut1 | PCutL | RANDFLOAT(0.00000000000000000001,1.00)
