<START_i+r+c> ::= <DEFINE-THRESHOLD-LEVEL_i+r+c> <MLC-ALGORITHMS_i+r+c>
<MLC-ALGORITHMS_i+r+c> ::= BR <ALGS-SLC_i+r+c> | CC <ALGS-SLC_i+r+c> | LP <ALGS-SLC_i+r+c> | <BRq_i+r+c> <ALGS-SLC_i+r+c> | <CCq_i+r+c> <ALGS-SLC_i+r+c> | FW <ALGS-SLC_i+r+c> | RT <ALGS-SLC_i+r+c> | PCC <ALGS-SLC_i+r+c> | <CT_i+r+c> <ALGS-SLC_i+r+c>| <MCC_i+r+c> <ALGS-SLC_i+r+c>| <CDT_i+r+c> <ALGS-SLC_i+r+c> | <CDN_i+r+c> <ALGS-SLC_i+r+c> | <PS_i+r+c> <ALGS-SLC_i+r+c> | <PSt_i+r+c> <ALGS-SLC_i+r+c> | <RAkEL_i+r+c> <ALGS-SLC_i+r+c> | <RAkELd_i+r+c> <ALGS-SLC_i+r+c> | <BCC_i+r+c> <ALGS-SLC_i+r+c> | <PMCC_i+r+c> <ALGS-SLC_i+r+c> | <ML-BPNN_i+r+c> | <ML-DBPNN_i+r+c> <ML-BPNN_i+r+c> | <HOMER_i+r+c> <META-MLC_i+r+c> | <MBR_i+r+c> 
<ALGS-SLC_i+r+c> ::= <ALGS-SLC-WITH-FS_i+r+c> | <ALG-TYPE-WITHOUT-FS_i+r+c> | <META-SLC_i+r+c>
<ALGS-SLC-WITH-FS_i+r+c> ::= <ASC_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c>
<ASC_i+r+c> ::= ASC <sm_i+r+c>
<ALG-TYPE-WITHOUT-FS_i+r+c> ::= <J48_i+r+c> | DecisionStump |  <RandomForest_i+r+c> | <RandomTree_i+r+c> | <REPTree_i+r+c> | <DT_i+r+c> | <JRip_i+r+c> | <OneR_i+r+c> | <PART_i+r+c> | ZeroR | <KNN_i+r+c> | <KStar_i+r+c> | <VotedPerceptron_i+r+c> | <MultiLayerPerc_i+r+c> | <SeqMinOptimization_i+r+c> | <StocGradDescent_i+r+c> | <LR_i+r+c> | <NB_i+r+c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees_i+r+c> | <SimpleLogistic_i+r+c>
<J48_i+r+c> ::= J48 <J48-Complement_i+r+c> <J48-Basics_i+r+c>
<J48-Complement_i+r+c> ::= <cf_i+r+c> <sr_i+r+c> | True
<cf_i+r+c> ::= RANDFLOAT(0.0,1.0)
<sr_i+r+c> ::= True | False
<J48-Basics_i+r+c> ::= <mno_i+r+c> <ct_i+r+c> <bs_i+r+c> <umc_i+r+c> <ul_i+r+c>
<mno_i+r+c> ::= RANDINT_TYPE0(1,64)
<ct_i+r+c> ::= True | False
<bs_i+r+c> ::= True | False
<umc_i+r+c> ::= True | False
<ul_i+r+c> ::= True | False
<RandomForest_i+r+c> ::= RandomForest <nt_i+r+c> <nf_i+r+c>  <md_i+r+c>
<nt_i+r+c> ::= RANDINT_TYPE0(2,256)
<nf_i+r+c> ::= RANDINT_TYPE0(2,32)
<md_i+r+c> ::= RANDINT_TYPE0(2,20)
<RandomTree_i+r+c> ::= RandomTree <mw_i+r+c> <nfbgt_i+r+c> <nf_i+r+c>  <md_i+r+c>
<mw_i+r+c> ::= RANDINT_TYPE0(1,64)
<nfbgt_i+r+c> ::= <growing_the_tree_and_backfitting_i+r+c>
<growing_the_tree_and_backfitting_i+r+c> ::= RANDINT_TYPE0(2,5)
<REPTree_i+r+c> ::= REPTree <var_i+r+c> <mw_i+r+c> <up_i+r+c>  <md_i+r+c>
<var_i+r+c> ::= RANDFLOAT(0.00001,0.1)
<up_i+r+c> ::= True | False
<DT_i+r+c> ::= DT <em_i+r+c> <uibk_i+r+c> <sm_i+r+c> <crv_i+r+c> 
<em_i+r+c> ::= acc | rmse | mae | auc
<uibk_i+r+c> ::= True | False
<sm_i+r+c> ::= GreedyStepwise | BestFirst
<crv_i+r+c> ::= 1 | 2 | 3 | 4
<JRip_i+r+c> ::= JRip <mtw_i+r+c> <cer_i+r+c> <up_i+r+c> <o_i+r+c> 
<mtw_i+r+c> ::= RANDFLOAT(1.0,5.0)
<cer_i+r+c> ::= True | False
<o_i+r+c> ::= RANDINT_TYPE0(1,5)
<OneR_i+r+c> ::= OneR <mbs_i+r+c>
<mbs_i+r+c> ::= RANDINT_TYPE0(1,32)
<PART_i+r+c> ::= PART <PART-BASICS_i+r+c> <PART-CONSTRAINTS_i+r+c>
<PART-BASICS_i+r+c> ::= <mno_i+r+c> <bs_i+r+c>
<PART-CONSTRAINTS_i+r+c> ::= True <nr_i+r+c> | False
<nr_i+r+c> ::= RANDINT_TYPE0(2,5)
<KNN_i+r+c> ::= KNN <k_nn_i+r+c> <loo_i+r+c> <dw_i+r+c>
<k_nn_i+r+c> ::= RANDINT_TYPE0(1,64)
<loo_i+r+c> ::= True | False
<dw_i+r+c> ::= F | I | None
<KStar_i+r+c> ::= KStar <gb_i+r+c> <eab_i+r+c> <mm_i+r+c>
<gb_i+r+c> ::= RANDINT_TYPE0(1,100)
<eab_i+r+c> ::= True | False
<mm_i+r+c> ::= a | d | m | n
<VotedPerceptron_i+r+c> ::= VotedPerceptron <i_i+r+c> <mk_i+r+c> <e_i+r+c>
<i_i+r+c> ::= RANDINT_TYPE0(1,10)
<mk_i+r+c> ::= RANDINT_TYPE0(5000,50000)
<e_i+r+c> ::= RANDFLOAT(0.2,5.0)
<MultiLayerPerc_i+r+c> ::= MultiLayerPerc <lr_i+r+c> <m_i+r+c> <nhn_i+r+c> <n2b_i+r+c> <reset_i+r+c> <decay_i+r+c>
<lr_i+r+c> ::= RANDFLOAT(0.1,1.0)
<m_i+r+c> ::= RANDFLOAT(0.0,1.0)
<nhn_i+r+c> ::= a | i | o | t
<n2b_i+r+c> ::= True | False
<reset_i+r+c> ::= True | False
<decay_i+r+c> ::= True | False
<LR_i+r+c> ::= LogisticRegression <r_i+r+c>
<StocGradDescent_i+r+c> ::= StocGradDescent <lf_i+r+c> <lr_sgd_i+r+c> <nn_i+r+c> <nrmv_i+r+c> <r_i+r+c>
<lf_i+r+c> ::= 0 | 1 | 2
<lr_sgd_i+r+c> ::= RANDFLOAT(0.00001,1.0)
<nn_i+r+c> ::= True | False
<nrmv_i+r+c> ::= True | False
<r_i+r+c> ::= RANDFLOAT(0.000000000001,10.0)
<SeqMinOptimization_i+r+c> ::= SeqMinOptimization <c_i+r+c> <ft_i+r+c> <bcm_i+r+c> <kernel_i+r+c>
<c_i+r+c> ::= RANDFLOAT(0.5,1.5)
<ft_i+r+c> ::= 0 | 1 | 2
<bcm_i+r+c> ::= True | False
<kernel_i+r+c> ::= <poly_kern_i+r+c> <exp_i+r+c> <ulo_i+r+c> | Puk <om_i+r+c> <sig_i+r+c> | RBFKernel <g_i+r+c>
<poly_kern_i+r+c> ::= NormalizedPolyKernel | PolyKernel
<exp_i+r+c> ::= RANDFLOAT(0.2,5.0)
<ulo_i+r+c> ::= True | False
<om_i+r+c> ::= RANDFLOAT(0.1,1.0)
<sig_i+r+c> ::= RANDFLOAT(0.1,10.0)
<g_i+r+c> ::= RANDFLOAT(0.0001,1.0)
<NB_i+r+c> ::= NaiveBayes <NB-Parameters_i+r+c>
<NB-Parameters_i+r+c> ::= uke | usd | None
<SimpleLogistic_i+r+c> ::= SimpleLogistic <ucv_i+r+c> <uaic_i+r+c> <wtb_activate_i+r+c>
<ucv_i+r+c> ::= True | False
<LogisticModelTrees_i+r+c> ::= LogisticModelTrees <mno_i+r+c> <cn_i+r+c> <sor_i+r+c> <fr_i+r+c> <eop_i+r+c> <uaic_i+r+c> <wtb_activate_i+r+c>
<cn_i+r+c> ::= True | False
<sor_i+r+c> ::= True | False
<fr_i+r+c> ::= True | False
<eop_i+r+c> ::= True | False
<wtb_activate_i+r+c> ::= True <wtb_i+r+c> | False
<uaic_i+r+c> ::= True | False
<wtb_i+r+c> ::= RANDFLOAT(0.0,1.0)
<META-SLC_i+r+c> ::= <LWL_i+r+c> <ALG-WEIGHTED-TYPE_i+r+c> | RandomSubspace <sss_i+r+c> <ni_random_methods_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | RandomCommittee <ni_random_methods_i+r+c> <ALG-TYPE_RC_i+r+c> | <Bagging_i+r+c> <ni_ada_and_bagging_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | <AdaM1_i+r+c> <ni_ada_and_bagging_i+r+c> <ALG-WEIGHTED-TYPE_i+r+c> | <STACKING_i+r+c> | <VOTING_i+r+c>
<ALG-WEIGHTED-TYPE_i+r+c> ::= <J48_i+r+c> | DecisionStump | <RandomForest_i+r+c> | <RandomTree_i+r+c> | <REPTree_i+r+c> | <DT_i+r+c> | <JRip_i+r+c> | <PART_i+r+c> | ZeroR | <KNN_i+r+c> | <NB_i+r+c> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc_i+r+c> |  <SeqMinOptimization_i+r+c> | <SimpleLogistic_i+r+c>
<LWL_i+r+c> ::= LWL <k_lwl_activate_i+r+c> <wk_activate_i+r+c>
<k_lwl_activate_i+r+c> ::= True <k_lwl_i+r+c> | False
<k_lwl_i+r+c> ::= -1 | 10| 30 | 60 | 90 | 120
<wk_activate_i+r+c> ::= True <wk_i+r+c> | False
<wk_i+r+c> ::= 0 | 1 | 2 | 3 | 4
<sss_i+r+c> ::= RANDFLOAT(0.1,1.0)
<ni_random_methods_i+r+c> ::= RANDINT_TYPE0(2,64)
<ALG-TYPE_RC_i+r+c> ::= <RandomForest_i+r+c> | <RandomTree_i+r+c> | <REPTree_i+r+c> | <StocGradDescent_i+r+c> | <MultiLayerPerc_i+r+c>
<Bagging_i+r+c> ::= BaggingSLC <BaggingSLC_BASICS_i+r+c>
<BaggingSLC_BASICS_i+r+c> ::= False <bsp-bagg_i+r+c> | True 100
<bsp-bagg_i+r+c> ::= RANDINT_TYPE0(10,100)
<AdaM1_i+r+c> ::= AdaM1 <wt_i+r+c> <ur_i+r+c>
<wt_i+r+c> ::= RANDINT_TYPE0(50,100) | 100
<ni_ada_and_bagging_i+r+c> ::= RANDINT_TYPE0(2,128)
<ur_i+r+c> ::= True | False
<STACKING_i+r+c> ::= Stacking <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | Stacking <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | Stacking <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | Stacking <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c>
<VOTING_i+r+c> ::= <Vote_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | <Vote_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | <Vote_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> | <Vote_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c> <ALG-TYPE-WITHOUT-FS_i+r+c>
<Vote_i+r+c> ::= Vote <cr_i+r+c>
<cr_i+r+c> ::= AVG | PROD | MAJ | MIN | MAX
<BRq_i+r+c> ::= BRq <dsr_i+r+c>
<CCq_i+r+c> ::= CCq <dsr_i+r+c>
<dsr_i+r+c> ::= RANDFLOAT(0.2,0.8)
<MCC_i+r+c> ::= MCC <chi_MCC_i+r+c> <ii_i+r+c> <eval_metrics_i+r+c>
<CDN_i+r+c> ::= CDN <i_cdn_cdt_i+r+c> <ci_i+r+c>
<chi_MCC_i+r+c>::= <chi_CT_i+r+c>
<ii_i+r+c> ::= RANDINT_TYPE0(2,100)
<eval_metrics_i+r+c> ::= Accuracy | Jaccard-index | Hamming-score | Exact-match | Jaccard-distance | Hamming-loss | ZeroOne-loss | Harmonic-score | One-error | Rank-loss | Avg-precision | Log-Loss-lim:L | Log-Loss-lim:D | Micro-Precision | Micro-Recall | Macro-Precision | Macro-Recall | F1-micro-averaged | F1-macro-averaged-by-example | F1-macro-averaged-by-label | AUPRC-macro-averaged | AUROC-macro-averaged | Levenshtein-distance
<CT_i+r+c> ::= CT <chi_CT_i+r+c> <w_i+r+c> <dp_i+r+c> <ii_i+r+c> <eval_metrics_i+r+c>
<chi_CT_i+r+c> ::= RANDINT_TYPE0(2,1500)
<dp_i+r+c> ::= C | I | Ib | Ibf | H | Hbf | X | F | None
<w_i+r+c> ::= 0 1 | -1 <d_i+r+c>
<d_i+r+c> ::= RANDINT_TYPE1(1,SQRT(L)+1)
<CDT_i+r+c> ::= CDT <w_i+r+c> <dp_i+r+c> <i_cdn_cdt_i+r+c> <ci_i+r+c>
<i_cdn_cdt_i+r+c> ::= RANDINT_TYPE0(101,1000)
<ci_i+r+c> ::= RANDINT_TYPE0(1,100)
<PS_i+r+c> ::= PS <sv_i+r+c> <pv_i+r+c>
<PSt_i+r+c> ::= PSt <sv_i+r+c> <pv_i+r+c>
<RAkELd_i+r+c> ::= RAkELd <les_i+r+c> <sv_i+r+c> <pv_i+r+c>
<RAkEL_i+r+c> ::= RAkEL <sre_i+r+c> <les_i+r+c> <sv_i+r+c> <pv_i+r+c>
<sv_i+r+c> ::= RANDINT_TYPE0(0,5)
<pv_i+r+c> ::= RANDINT_TYPE0(1,5)
<les_i+r+c> ::= RANDINT_TYPE2(1,L/2)
<sre_i+r+c> ::= RANDINT_TYPE3(2,min(2L;100))
<BCC_i+r+c> ::= BCC <dp_complete_i+r+c>
<dp_complete_i+r+c> ::= L | <dp_i+r+c>
<B_i+r+c> ::= RANDFLOAT(0.01,0.99)
<ts_i+r+c> ::= 0 | 1
<chi_PMCC_i+r+c> ::= RANDINT_TYPE0(51,1500)
<ps_i+r+c> ::= RANDINT_TYPE0(1,50)
<PMCC_i+r+c> ::= PMCC <B_i+r+c> <ts_i+r+c> <ii_i+r+c> <chi_PMCC_i+r+c> <ps_i+r+c> <eval_metrics_i+r+c>
<ML-BPNN_i+r+c> ::= ML-BPNN <ne_i+r+c> <nhu_bpnn_i+r+c> <lr_bpnn_i+r+c> <m_bpnn_i+r+c>
<ne_i+r+c> ::= RANDINT_TYPE0(10,1000)
<nhu_bpnn_i+r+c> ::= RANDINT_TYPE4((0.2,1.0)*n_attributes)
<lr_bpnn_i+r+c> ::= RANDFLOAT(0.001,0.1)
<m_bpnn_i+r+c> ::=  RANDFLOAT(0.2,0.8)
<ML-DBPNN_i+r+c> ::= ML-DBPNN <ne_i+r+c> <nhu_bpnn_i+r+c> <lr_bpnn_i+r+c> <m_bpnn_i+r+c> <rbm_i+r+c>		
<rbm_i+r+c> ::= RANDINT_TYPE0(2,5)
<HOMER_i+r+c> ::= HOMER <t_i+r+c> <k_homer_i+r+c>
<t_i+r+c> ::= BalancedClustering | Clustering | Random
<k_homer_i+r+c> ::= RANDINT_TYPE6(2,L-1)
<META-MLC_i+r+c> ::= BR <ALGS-SLC_i+r+c> | CC <ALGS-SLC_i+r+c> | LP <ALGS-SLC_i+r+c>
<MBR_i+r+c> ::= MBR BR <<ALGS-SLC_i+r+c>
<DEFINE-THRESHOLD-LEVEL_i+r+c> ::= threshold <predtshd_i+r+c>
<predtshd_i+r+c> ::= PCut1 | PCutL | RANDFLOAT(0.00000000000000000001,1.00)
