grammar += "<START> ::= <DEFINE-THRESHOLD-LEVEL> <MLC-ALGORITHMS>"+"\n";
grammar += "<MLC-ALGORITHMS> ::= BR <ALGS-SLC> | CC <ALGS-SLC> | LP <ALGS-SLC> | <BRq> <ALGS-SLC> | <CCq> <ALGS-SLC> | FW <ALGS-SLC> | RT <ALGS-SLC> | PCC <ALGS-SLC> | <CT> <ALGS-SLC>| <MCC> <ALGS-SLC>| <CDT> <ALGS-SLC> | <CDN> <ALGS-SLC> | <PS> <ALGS-SLC> | <PSt> <ALGS-SLC> | <RAkEL> <ALGS-SLC> | <RAkELd> <ALGS-SLC> | <BCC> <ALGS-SLC> | <PMCC> <ALGS-SLC> | <ML-BPNN> | <ML-DBPNN> <ML-BPNN> | <HOMER> <META-MLC> | <MBR> "+"\n";
grammar += "<ALGS-SLC> ::= <ALGS-SLC-WITH-FS> | <ALG-TYPE-WITHOUT-FS> | <META-SLC>"+"\n";
grammar += "<ALGS-SLC-WITH-FS> ::= <ASC> <ALG-TYPE-WITHOUT-FS>"+"\n";
grammar += "<ASC> ::= ASC <sm>"+"\n";
grammar += "<ALG-TYPE-WITHOUT-FS> ::= <J48> | DecisionStump |  <RandomForest> | <RandomTree> | <REPTree> | <DT> | <JRip> | <OneR> | <PART> | ZeroR | <KNN> | <KStar> | <VotedPerceptron> | <MultiLayerPerc> | <SeqMinOptimization> | <StocGradDescent> | <LR> | <NB> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <LogisticModelTrees> | <SimpleLogistic>"+"\n";
grammar += "<J48> ::= J48 <J48-Complement> <J48-Basics>"+"\n";
grammar += "<J48-Complement> ::= <cf> <sr> | True"+"\n";
grammar += "<cf> ::= 0.25"+"\n";
grammar += "<sr> ::= True | False"+"\n";
grammar += "<J48-Basics> ::= <mno> <ct> <bs> <umc> <ul>"+"\n";
grammar += "<mno> ::= RANDINT_TYPE0(1,64)"+"\n";
grammar += "<ct> ::= True | False"+"\n";
grammar += "<bs> ::= True | False"+"\n";
grammar += "<umc> ::= True | False"+"\n";
grammar += "<ul> ::= True | False"+"\n";
grammar += "<RandomForest> ::= RandomForest <nt> <nf>  <md>"+"\n";
grammar += "<nt> ::= RANDINT_TYPE0(2,256)"+"\n";
grammar += "<nf> ::= RANDINT_TYPE0(2,32)"+"\n";
grammar += "<md> ::= RANDINT_TYPE0(2,20)"+"\n";
grammar += "<RandomTree> ::= RandomTree <mw> <nfbgt> <nf>  <md>"+"\n";
grammar += "<mw> ::= RANDINT_TYPE0(1,64)"+"\n";
grammar += "<nfbgt> ::= <growing_the_tree_and_backfitting>"+"\n";
grammar += "<growing_the_tree_and_backfitting> ::= RANDINT_TYPE0(2,5)"+"\n";
grammar += "<REPTree> ::= REPTree <var> <mw> <up>  <md>"+"\n";
grammar += "<var> ::= 0.001"+"\n";
grammar += "<up> ::= True | False"+"\n";
grammar += "<DT> ::= DT <em> <uibk> <sm> <crv> "+"\n";
grammar += "<em> ::= acc | rmse | mae | auc"+"\n";
grammar += "<uibk> ::= True | False"+"\n";
grammar += "<sm> ::= GreedyStepwise | BestFirst"+"\n";
grammar += "<crv> ::= 1 | 2 | 3 | 4"+"\n";
grammar += "<JRip> ::= JRip <mtw> <cer> <up> <o> "+"\n";
grammar += "<mtw> ::=  2.0"+"\n";
grammar += "<cer> ::= True | False"+"\n";
grammar += "<o> ::= RANDINT_TYPE0(1,5)"+"\n";
grammar += "<OneR> ::= OneR <mbs>"+"\n";
grammar += "<mbs> ::= RANDINT_TYPE0(1,32)"+"\n";
grammar += "<PART> ::= PART <PART-BASICS> <PART-CONSTRAINTS>"+"\n";
grammar += "<PART-BASICS> ::= <mno> <bs>"+"\n";
grammar += "<PART-CONSTRAINTS> ::= True <nr> | False"+"\n";
grammar += "<nr> ::= RANDINT_TYPE0(2,5)"+"\n";
grammar += "<KNN> ::= KNN <k_nn> <loo> <dw>"+"\n";
grammar += "<k_nn> ::= RANDINT_TYPE0(1,64)"+"\n";
grammar += "<loo> ::= True | False"+"\n";
grammar += "<dw> ::= F | I | None"+"\n";
grammar += "<KStar> ::= KStar <gb> <eab> <mm>"+"\n";
grammar += "<gb> ::= RANDINT_TYPE0(1,100)"+"\n";
grammar += "<eab> ::= True | False"+"\n";
grammar += "<mm> ::= a | d | m | n"+"\n";
grammar += "<VotedPerceptron> ::= VotedPerceptron <i> <mk> <e>"+"\n";
grammar += "<i> ::= RANDINT_TYPE0(1,10)"+"\n";
grammar += "<mk> ::= RANDINT_TYPE0(5000,50000)"+"\n";
grammar += "<e> ::= 1.0"+"\n";
grammar += "<MultiLayerPerc> ::= MultiLayerPerc <lr> <m> <nhn> <n2b> <reset> <decay>"+"\n";
grammar += "<lr> ::= 0.3"+"\n";
grammar += "<m> ::= 0.2"+"\n";
grammar += "<nhn> ::= a | i | o | t"+"\n";
grammar += "<n2b> ::= True | False"+"\n";
grammar += "<reset> ::= True | False"+"\n";
grammar += "<decay> ::= True | False"+"\n";
grammar += "<LR> ::= LogisticRegression <r-lr>"+"\n";
grammar += "<r-lr> ::= 0.00000001"+"\n";
grammar += "<StocGradDescent> ::= StocGradDescent <lf> <lr_sgd> <nn> <nrmv> <r>"+"\n";
grammar += "<lf> ::= 0 | 1 | 2"+"\n";
grammar += "<lr_sgd> ::= 0.01"+"\n";
grammar += "<nn> ::= True | False"+"\n";
grammar += "<nrmv> ::= True | False"+"\n";
grammar += "<r> ::= 0.0001"+"\n";
grammar += "<SeqMinOptimization> ::= SeqMinOptimization <c> <ft> <bcm> <kernel>"+"\n";
grammar += "<c> ::= 1.0"+"\n";
grammar += "<ft> ::= 0 | 1 | 2"+"\n";
grammar += "<bcm> ::= True | False"+"\n";
grammar += "<kernel> ::= <poly_kern> <exp> <ulo> | Puk <om> <sig> | RBFKernel <g>"+"\n";
grammar += "<poly_kern> ::= NormalizedPolyKernel | PolyKernel"+"\n";
grammar += "<exp> ::= 1.0"+"\n";
grammar += "<ulo> ::= True | False"+"\n";
grammar += "<om> ::= 1.0"+"\n";
grammar += "<sig> ::= 1.0"+"\n";
grammar += "<g> ::= 0.01"+"\n";
grammar += "<NB> ::= NaiveBayes <NB-Parameters>"+"\n";
grammar += "<NB-Parameters> ::= uke | usd | None"+"\n";
grammar += "<SimpleLogistic> ::= SimpleLogistic <ucv> <uaic> <wtb_activate>"+"\n";
grammar += "<ucv> ::= True | False"+"\n";
grammar += "<LogisticModelTrees> ::= LogisticModelTrees <mno> <cn> <sor> <fr> <eop> <uaic> <wtb_activate>"+"\n";
grammar += "<cn> ::= True | False"+"\n";
grammar += "<sor> ::= True | False"+"\n";
grammar += "<fr> ::= True | False"+"\n";
grammar += "<eop> ::= True | False"+"\n";
grammar += "<wtb_activate> ::= True <wtb> | False"+"\n";
grammar += "<uaic> ::= True | False"+"\n";
grammar += "<wtb> ::= 0.0"+"\n";
grammar += "<META-SLC> ::= <LWL> <ALG-WEIGHTED-TYPE> | RandomSubspace <sss> <ni_random_methods> <ALG-TYPE-WITHOUT-FS> | RandomCommittee <ni_random_methods> <ALG-TYPE_RC> | <Bagging> <ni_ada_and_bagging> <ALG-TYPE-WITHOUT-FS> | <AdaM1> <ni_ada_and_bagging> <ALG-WEIGHTED-TYPE> | <STACKING> | <VOTING>"+"\n";
grammar += "<ALG-WEIGHTED-TYPE> ::= <J48> | DecisionStump | <RandomForest> | <RandomTree> | <REPTree> | <DT> | <JRip> | <PART> | ZeroR | <KNN> | <NB> | TAN | K2 | HillClimber | LAGDHillClimber | SimulatedAnnealing | TabuSearch | NaiveBayesMultinomial | <MultiLayerPerc> |  <SeqMinOptimization> | <SimpleLogistic>"+"\n";
grammar += "<LWL> ::= LWL <k_lwl_activate> <wk_activate>"+"\n";
grammar += "<k_lwl_activate> ::= True <k_lwl> | False"+"\n";
grammar += "<k_lwl> ::= -1 | 10| 30 | 60 | 90 | 120"+"\n";
grammar += "<wk_activate> ::= True <wk> | False"+"\n";
grammar += "<wk> ::= 0 | 1 | 2 | 3 | 4"+"\n";
grammar += "<sss> ::= 0.5"+"\n";
grammar += "<ni_random_methods> ::= RANDINT_TYPE0(2,64)"+"\n";
grammar += "<ALG-TYPE_RC> ::= <RandomForest> | <RandomTree> | <REPTree> | <StocGradDescent> | <MultiLayerPerc>"+"\n";
grammar += "<Bagging> ::= BaggingSLC <BaggingSLC_BASICS>"+"\n";
grammar += "<BaggingSLC_BASICS> ::= False <bsp-bagg> | True 100"+"\n";
grammar += "<bsp-bagg> ::= RANDINT_TYPE0(10,100)"+"\n";
grammar += "<AdaM1> ::= AdaM1 <wt> <ur>"+"\n";
grammar += "<wt> ::= RANDINT_TYPE0(50,100) | 100"+"\n";
grammar += "<ni_ada_and_bagging> ::= RANDINT_TYPE0(2,128)"+"\n";
grammar += "<ur> ::= True | False"+"\n";
grammar += "<STACKING> ::= Stacking <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | Stacking <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | Stacking <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | Stacking <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS>"+"\n";
grammar += "<VOTING> ::= <Vote> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | <Vote> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | <Vote> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> | <Vote> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS> <ALG-TYPE-WITHOUT-FS>"+"\n";
grammar += "<Vote> ::= Vote <cr>"+"\n";
grammar += "<cr> ::= AVG | PROD | MAJ | MIN | MAX"+"\n";
grammar += "<BRq> ::= BRq <dsr>"+"\n";
grammar += "<CCq> ::= CCq <dsr>"+"\n";
grammar += "<dsr> ::= 0.75"+"\n";
grammar += "<MCC> ::= MCC <chi_MCC> <ii> <eval_metrics>"+"\n";
grammar += "<CDN> ::= CDN <i_cdn_cdt> <ci>"+"\n";
grammar += "<chi_MCC>::= <chi_CT>"+"\n";
grammar += "<ii> ::= RANDINT_TYPE0(2,100)"+"\n";
grammar += "<eval_metrics> ::= Accuracy | Jaccard-index | Hamming-score | Exact-match | Jaccard-distance | Hamming-loss | ZeroOne-loss | Harmonic-score | One-error | Rank-loss | Avg-precision | Log-Loss-lim:L | Log-Loss-lim:D | Micro-Precision | Micro-Recall | Macro-Precision | Macro-Recall | F1-micro-averaged | F1-macro-averaged-by-example | F1-macro-averaged-by-label | AUPRC-macro-averaged | AUROC-macro-averaged | Levenshtein-distance"+"\n";
grammar += "<CT> ::= CT <chi_CT> <w> <dp> <ii> <eval_metrics>"+"\n";
grammar += "<chi_CT> ::= RANDINT_TYPE0(2,1500)"+"\n";
grammar += "<dp> ::= C | I | Ib | Ibf | H | Hbf | X | F | None"+"\n";
grammar += "<w> ::= 0 1 | -1 <d>"+"\n";
grammar += "<d> ::= RANDINT_TYPE1(1,SQRT(L)+1)"+"\n";
grammar += "<CDT> ::= CDT <w> <dp> <i_cdn_cdt> <ci>"+"\n";
grammar += "<i_cdn_cdt> ::= RANDINT_TYPE0(101,1000)"+"\n";
grammar += "<ci> ::= RANDINT_TYPE0(1,100)"+"\n";
grammar += "<PS> ::= PS <sv> <pv>"+"\n";
grammar += "<PSt> ::= PSt <sv> <pv>"+"\n";
grammar += "<RAkELd> ::= RAkELd <les> <sv> <pv>"+"\n";
grammar += "<RAkEL> ::= RAkEL <sre> <les> <sv> <pv>"+"\n";
grammar += "<sv> ::= RANDINT_TYPE0(0,5)"+"\n";
grammar += "<pv> ::= RANDINT_TYPE0(1,5)"+"\n";
grammar += "<les> ::= RANDINT_TYPE2(1,L/2)"+"\n";
grammar += "<sre> ::= RANDINT_TYPE3(2,min(2L;100))"+"\n";
grammar += "<BCC> ::= BCC <dp_complete>"+"\n";
grammar += "<dp_complete> ::= L | <dp>"+"\n";
grammar += "<B> ::= 0.03"+"\n";
grammar += "<ts> ::= 0 | 1"+"\n";
grammar += "<chi_PMCC> ::= RANDINT_TYPE0(51,1500)"+"\n";
grammar += "<ps> ::= RANDINT_TYPE0(1,50)"+"\n";
grammar += "<PMCC> ::= PMCC <B> <ts> <ii> <chi_PMCC> <ps> <eval_metrics>"+"\n";
grammar += "<ML-BPNN> ::= ML-BPNN <ne> <nhu_bpnn> <lr_bpnn> <m_bpnn>"+"\n";
grammar += "<ne> ::= RANDINT_TYPE0(10,1000)"+"\n";
grammar += "<nhu_bpnn> ::= RANDINT_TYPE4((0.2,1.0)*n_attributes)"+"\n";
grammar += "<lr_bpnn> ::= 0.1"+"\n";
grammar += "<m_bpnn> ::=  0.1"+"\n";
grammar += "<ML-DBPNN> ::= ML-DBPNN <ne> <nhu_bpnn> <lr_bpnn> <m_bpnn> <rbm>		"+"\n";
grammar += "<rbm> ::= RANDINT_TYPE0(2,5)"+"\n";
grammar += "<HOMER> ::= HOMER <t> <k_homer>"+"\n";
grammar += "<t> ::= BalancedClustering | Clustering | Random"+"\n";
grammar += "<k_homer> ::= RANDINT_TYPE6(2,L-1)"+"\n";
grammar += "<META-MLC> ::= BR <ALGS-SLC> | CC <ALGS-SLC> | LP <ALGS-SLC>"+"\n";
grammar += "<MBR> ::= MBR BR <<ALGS-SLC>"+"\n";
grammar += "<DEFINE-THRESHOLD-LEVEL> ::= threshold <predtshd>"+"\n";
grammar += "<predtshd> ::= PCut1 | PCutL | 0.5"+"\n";
